const a11 = {
    /**
     * Represents a test. Each test has an id,
     * an English, Math, Reading, and Science section.
     * Each section contains a score scale and an array
     * of questions. Questions indicate correct answers
     * and question type.
     */
    id: 'a11',
    english:{
        scorescale: [1, 1, 2, 3, 3, 4, 5, 5, 
                    6, 6, 7, 7, 8, 8, 9, 9, 9, 
                    10, 10, 10, 11, 11, 11, 12, 
                    12, 13, 13, 14, 14, 14, 15, 
                    15, 15, 15, 16, 16, 16, 17, 
                    17, 17, 18, 19, 19, 20, 20, 
                    20, 21, 21, 21, 22, 22, 22, 
                    23, 23, 23, 24, 24, 25, 25, 
                    25, 26, 27, 27, 28, 29, 30, 
                    31, 32, 33, 34, 34, 35, 35, 
                    36, 36, 36],
        questions: [['c', 'verb tense'],
                    ['c', 'inference'],
                    ['d', 'conciseness'],
                    ['b', 'omit/delete'],
                    ['d', 'conciseness'],
                    ['d', 'verb tense'],
                    ['b', 'transitions'],
                    ['c', 'punctuation'],
                    ['c', 'verb tense'],
                    ['a', 'verb tense'],
                    ['a', 'punctuation'],
                    ['d', 'placement'],
                    ['d', 'conciseness'],
                    ['c', 'yes/no'],
                    ['b', 'placement'],
                    ['d', 'omit/delete'],
                    ['a', 'conciseness'],
                    ['b', 'punctuation'],
                    ['a', 'prepositions'],
                    ['c', 'verb tense'],
                    ['a', 'punctuation'],
                    ['d', 'verb tense'],
                    ['c', 'prepositions'],
                    ['a', 'passive voice'],
                    ['b', 'inference'],
                    ['d', 'placement'],
                    ['d', 'prepositions'],
                    ['c', 'punctuation'],
                    ['b', 'placement'],
                    ['b', 'yes/no'],
                    ['a', 'conciseness'],
                    ['c', 'transitions'],
                    ['c', 'punctuation'],
                    ['d', 'inference'],
                    ['d', 'conciseness'],
                    ['a', 'inference'],
                    ['a', 'pronouns'],
                    ['a', 'punctuation'],
                    ['d', 'placement'],
                    ['b', 'yes/no'],
                    ['c', 'passive voice'],
                    ['c', 'inference'],
                    ['b', 'transitions'],
                    ['c', 'vocab in context'],
                    ['a', 'inference'],
                    ['b', 'inference'],
                    ['a', 'inference'],
                    ['d', 'punctuation'],
                    ['d', 'verb tense'],
                    ['c', 'pronouns'],
                    ['b', 'ambiguity / vagueness'],
                    ['d', 'inference'],
                    ['b', 'conciseness'],
                    ['a', 'conciseness'],
                    ['b', 'punctuation'],
                    ['a', 'inference'],
                    ['c', 'yes/no'],
                    ['c', 'conciseness'],
                    ['d', 'placement'],
                    ['b', 'yes/no'],
                    ['b', 'conciseness'],
                    ['a', 'conciseness'],
                    ['a', 'possessives'],
                    ['c', 'inference'],
                    ['a', 'inference'],
                    ['a', 'inference'],
                    ['c', 'punctuation'],
                    ['d', 'vocab in context'],
                    ['b', 'punctuation'],
                    ['b', 'vocab in context'],
                    ['d', 'modifying clauses'],
                    ['d', 'possessives'],
                    ['a', 'conciseness'],
                    ['c', 'inference'],
                    ['c', 'yes/no']]
    },
    math: {
        scorescale: [1, 4, 7, 9, 
                    10, 11, 12, 13, 
                    13, 14, 14, 14, 
                    15, 15, 15, 16, 
                    16, 16, 16, 17,
                    17, 17, 18, 18, 
                    19, 19, 19, 20, 
                    20, 21, 22, 22, 
                    23, 23, 24, 24, 
                    25, 25, 25, 26, 
                    26, 26, 27, 27, 27, 
                    28, 28, 28, 29, 29, 
                    30, 30, 31, 32, 33, 
                    33, 34, 35, 35, 36, 36],
        questions: [['d', '1-20'],
                    ['c', '1-20'],
                    ['c', '1-20'],
                    ['d', '1-20'],
                    ['a', '1-20'],
                    ['c', '1-20'],
                    ['d', '1-20'],
                    ['c', '1-20'],
                    ['b', '1-20'],
                    ['b', '1-20'],
                    ['a', '1-20'],
                    ['b', '1-20'],
                    ['c', '1-20'],
                    ['a', '1-20'],
                    ['c', '1-20'],
                    ['e', '1-20'],
                    ['a', '1-20'],
                    ['e', '1-20'],
                    ['a', '1-20'],
                    ['b', '1-20'],
                    ['d', '21-40'],
                    ['d', '21-40'],
                    ['e', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['d', '21-40'],
                    ['d', '21-40'],
                    ['b', '21-40'],
                    ['e', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['b', '21-40'],
                    ['e', '21-40'],
                    ['e', '21-40'],
                    ['b', '21-40'],
                    ['c', '21-40'],
                    ['a', '21-40'],
                    ['a', '21-40'],
                    ['e', '21-40'],
                    ['e', '41-60'],
                    ['a', '41-60'],
                    ['a', '41-60'],
                    ['d', '41-60'],
                    ['d', '41-60'],
                    ['e', '41-60'],
                    ['a', '41-60'],
                    ['e', '41-60'],
                    ['d', '41-60'],
                    ['b', '41-60'],
                    ['d', '41-60'],
                    ['c', '41-60'],
                    ['b', '41-60'],
                    ['b', '41-60'],
                    ['d', '41-60'],
                    ['e', '41-60'],
                    ['b', '41-60'],
                    ['a', '41-60'],
                    ['d', '41-60'],
                    ['b', '41-60']]
    },
    reading: {
        scorescale: [1, 2, 4, 5, 7, 8, 9, 10, 
                    11, 12, 12, 13, 13, 14, 15, 
                    15, 16, 17, 17, 18, 19, 20, 
                    20, 21, 22, 22, 23, 24, 25, 
                    26, 27, 28, 29, 30, 31, 32, 
                    33, 34, 35, 35, 36 ],
        questions: [['b', 'inference'],
                    ['a', 'inference'],
                    ['d', 'inference'],
                    ['d', 'inference'],
                    ['b', 'detail'],
                    ['c', 'purpose'],
                    ['a', 'inference'],
                    ['d', 'detail'],
                    ['d', 'detail'],
                    ['c', 'inference'],
                    ['d', 'purpose'],
                    ['d', 'inference'],
                    ['d', 'inference'],
                    ['c', 'inference'],
                    ['b', 'purpose'],
                    ['c', 'detail'],
                    ['c', 'inference'],
                    ['d', 'big picture'],
                    ['c', 'inference'],
                    ['a', 'big picture'],
                    ['d', 'inference'],
                    ['c', 'detail'],
                    ['a', 'detail'],
                    ['a', 'inference'],
                    ['b', 'vocab in context'],
                    ['d', 'inference'],
                    ['a', 'detail'],
                    ['b', 'inference'],
                    ['c', 'detail'],
                    ['c', 'detail'],
                    ['b', 'big picture'],
                    ['a', 'inference'],
                    ['d', 'detail'],
                    ['b', 'inference'],
                    ['c', 'detail'],
                    ['a', 'purpose'],
                    ['a', 'detail'],
                    ['c', 'inference'],
                    ['a', 'purpose'],
                    ['b', 'vocab in context']]
    },
    science: {
        scorescale: [1, 3, 5, 6, 8, 9, 
                    10, 11, 12, 13, 14, 
                    14, 15, 16, 17, 17, 
                    18, 19, 19, 20, 21, 
                    21, 22, 22, 23, 24, 
                    24, 25, 25, 26, 27, 
                    28, 29, 30, 31, 32, 
                    33, 34, 35, 36, 36],
        questions: [['b', 'detail'],
                    ['d', 'detail'],
                    ['a', 'detail'],
                    ['c', 'trend'],
                    ['a', 'trend'],
                    ['c', 'new information'],
                    ['d', 'detail'],
                    ['d', 'detail'],
                    ['c', 'detail'],
                    ['c', 'detail'],
                    ['d', 'method'],
                    ['a', 'detail'],
                    ['b', 'detail'],
                    ['c', 'detail'],
                    ['b', 'detail'],
                    ['b', 'detail'],
                    ['c', 'trend'],
                    ['d', 'new information'],
                    ['a', 'new information'],
                    ['a', 'trend'],
                    ['c', 'trend'],
                    ['a', 'trend'],
                    ['d', 'detail'],
                    ['a', 'new information'],
                    ['b', 'detail'],
                    ['b', 'outside information'],
                    ['c', 'method'],
                    ['a', 'detail'],
                    ['b', 'new information'],
                    ['b', 'new information'],
                    ['a', 'new information'],
                    ['c', 'new information'],
                    ['d', 'new information'],
                    ['d', 'detail'],
                    ['c', 'detail'],
                    ['c', 'new information'],
                    ['b', 'detail'],
                    ['b', 'method'],
                    ['c', 'trend'],
                    ['d', 'trend']]
    },
}

const e73 = {
    id: '73e',
    english:{
        scorescale: [
                        1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 9, 9, 10, 10, 10,
                        11, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 16, 16, 16, 17,
                        17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23,
                        24, 24, 24, 25, 25, 25, 26, 26, 27, 27, 28, 29, 29, 30, 31, 32, 33,
                        34, 34, 35, 35, 36, 36
                    ],
        questions: [['d', 'punctuation'],
                    ['d', 'possessives'],
                    ['b', 'pronouns'],
                    ['a', 'inference'],
                    ['c', 'inference'],
                    ['c', 'pronouns'],
                    ['a', 'vocab in context'],
                    ['c', 'conciseness'],
                    ['c', 'omit/delete'],
                    ['a', 'prepositions'],
                    ['d', 'omit/delete'],
                    ['d', 'conciseness'],
                    ['b', 'punctuation'],
                    ['d', 'placement'],
                    ['c', 'yes/no'],
                    ['d', 'transitions'],
                    ['a', 'inference'],
                    ['b', 'punctuation'],
                    ['a', 'inference'],
                    ['c', 'transitions'],
                    ['d', 'pronouns'],
                    ['c', 'verb tense'],
                    ['a', 'punctuation'],
                    ['c', 'punctuation'],
                    ['d', 'conciseness'],
                    ['b', 'placement'],
                    ['a', 'punctuation'],
                    ['a', 'punctuation'],
                    ['b', 'inference'],
                    ['b', 'placement'],
                    ['a', 'punctuation'],
                    ['c', 'punctuation'],
                    ['a', 'subject/verb agreement'],
                    ['b', 'punctuation'],
                    ['c', 'yes/no'],
                    ['b', 'inference'],
                    ['d', 'inference'],
                    ['a', 'vocab in context'],
                    ['b', 'inference'],
                    ['c', 'verb tense'],
                    ['d', 'adjectives / adverbs'],
                    ['b', 'transitions'],
                    ['a', 'verb tense'],
                    ['b', 'inference'],
                    ['c', 'punctuation'], 
                    ['d', 'conciseness'],
                    ['b', 'possessives'],
                    ['a', 'punctuation'],
                    ['d', 'conciseness'],
                    ['d', 'conciseness'],
                    ['b', 'yes/no'],
                    ['d', 'punctuation'],
                    ['c', 'yes/no'],
                    ['b', 'subject/verb agreement'],
                    ['d', 'conciseness'],
                    ['a', 'parallelism'],
                    ['b', 'inference'],
                    ['b', 'omit/delete'],
                    ['a', 'inference'],
                    ['b', 'placement'],
                    ['d', 'conciseness'],
                    ['b', 'vocab in context'],
                    ['d', 'transitions'],
                    ['c', 'placement'],
                    ['b', 'punctuation'],
                    ['b', 'transitions'],
                    ['c', 'conciseness'],
                    ['a', 'ambiguity / vagueness'],
                    ['b', 'inference'],
                    ['c', 'transitions'],
                    ['a', 'comparisons'],
                    ['c', 'punctuation'],
                    ['d', 'punctuation'],
                    ['d', 'adjectives / adverbs'],
                    ['b', 'inference']]
    },
    math: {
        scorescale: [
                        1, 3, 5, 7, 9, 10, 11, 11, 12, 13, 13, 13, 14, 14,
                        15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18,
                        18, 19, 19, 20, 21, 21, 22, 22, 23, 23, 24, 24, 24,
                        25, 25, 26, 26, 26, 27, 27, 27, 28, 28, 29, 29, 30,
                        31, 32, 33, 33, 34, 35, 36, 36
                    ],
        questions: [['c', '1-20'],
                    ['d', '1-20'],
                    ['a', '1-20'],
                    ['a', '1-20'],
                    ['c', '1-20'],
                    ['e', '1-20'],
                    ['a', '1-20'],
                    ['b', '1-20'],
                    ['e', '1-20'],
                    ['d', '1-20'],
                    ['b', '1-20'],
                    ['d', '1-20'],
                    ['b', '1-20'],
                    ['b', '1-20'],
                    ['e', '1-20'],
                    ['d', '1-20'],
                    ['e', '1-20'],
                    ['b', '1-20'],
                    ['a', '1-20'],
                    ['c', '1-20'],
                    ['d', '21-40'],
                    ['d', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['b', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['a', '21-40'],
                    ['a', '21-40'],
                    ['e', '21-40'],
                    ['e', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['a', '21-40'],
                    ['e', '21-40'],
                    ['a', '21-40'],
                    ['b', '21-40'],
                    ['e', '21-40'],
                    ['b', '41-60'],
                    ['d', '41-60'],
                    ['a', '41-60'],
                    ['c', '41-60'],
                    ['a', '41-60'],
                    ['e', '41-60'],
                    ['d', '41-60'],
                    ['d', '41-60'],
                    ['a', '41-60'],
                    ['b', '41-60'],
                    ['d', '41-60'],
                    ['b', '41-60'],
                    ['d', '41-60'],
                    ['e', '41-60'],
                    ['c', '41-60'],
                    ['b', '41-60'],
                    ['b', '41-60'],
                    ['e', '41-60'],
                    ['d', '41-60'],
                    ['d', '41-60']]
    },
    reading: {
        scorescale: [
                        1, 2, 4, 5, 7, 8, 9, 10, 11, 12, 12, 13, 13, 
                        14, 15, 16, 16, 17, 18, 19, 19, 20, 21, 21,
                        22, 22, 23, 24, 24, 25, 26, 27, 28, 29, 30,
                        31, 32, 33, 34, 35, 36
                    ],
        questions: [['b', 'inference'],
        ['a', 'inference'],
        ['d', 'detail'],
        ['a', 'inference'],
        ['d', 'detail'],
        ['b', 'inference'],
        ['c', 'detail'],
        ['d', 'detail'],
        ['b', 'detail'],
        ['c', 'detail'],
        ['c', 'purpose'],
        ['b', 'big picture'],
        ['b', 'big picture'],
        ['b', 'detail'],
        ['d', 'purpose'],
        ['c', 'detail'],
        ['d', 'detail'],
        ['d', 'detail'],
        ['a', 'detail'],
        ['a', 'vocab in context'],
        ['d', 'purpose'],
        ['b', 'inference'],
        ['b', 'detail'],
        ['d', 'purpose'],
        ['c', 'inference'],
        ['b', 'purpose'],
        ['a', 'detail'],
        ['a', 'big picture'],
        ['a', 'inference'],
        ['d', 'purpose'],
        ['a', 'detail'],
        ['c', 'purpose'],
        ['d', 'purpose'],
        ['b', 'detail'],
        ['c', 'detail'],
        ['d', 'detail'],
        ['b', 'inference'],
        ['c', 'detail'],
        ['a', 'detail'],
        ['a', 'detail']]
    },
    science: {
        scorescale: [
                        1, 3, 5, 7, 8, 9, 10, 12, 12, 13, 14, 15, 16, 16, 
                        17, 18, 18, 19, 20, 20, 21, 22, 22, 23, 23, 24, 24,
                        25, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 35, 36, 36
                    ],
        questions: [['c', 'detail'],
                    ['d', 'detail'],
                    ['a', 'detail'],
                    ['c', 'detail'],
                    ['b', 'detail'],
                    ['b', 'trend'],
                    ['c', 'inference'],
                    ['a', 'new information'],
                    ['a', 'detail'],
                    ['a', 'detail'],
                    ['c', 'inference'],
                    ['d', 'new information'],
                    ['c', 'inference'],
                    ['b', 'inference'],
                    ['a', 'new information'],
                    ['d', 'detail'],
                    ['d', 'detail'],
                    ['d', 'detail'],
                    ['a', 'outside information'],
                    ['b', 'inference'],
                    ['b', 'new information'],
                    ['c', 'detail'],
                    ['c', 'inference'],
                    ['d', 'detail'],
                    ['a', 'detail'],
                    ['d', 'new information'],
                    ['a', 'detail'],
                    ['b', 'new information'],
                    ['b', 'detail'],
                    ['b', 'detail'],
                    ['c', 'new information'],
                    ['d', 'inference'],
                    ['d', 'inference'],
                    ['c', 'inference'],
                    ['a', 'detail'],
                    ['b', 'new information'],
                    ['d', 'inference'],
                    ['d', 'detail'],
                    ['b', 'outside information'],
                    ['a', 'detail']]
    },
}

const f67 = {
    id: '67f',
    english:{
        scorescale: [
                        1, 1, 1, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 8,
                        9, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 14, 15, 15,
                        16, 16, 16, 17, 17, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21,
                        21, 21, 22, 22, 23, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27,
                        28, 29, 29, 30, 31, 32, 33, 34, 35, 36
                    ],
        questions: [
                        ['d','punctuation'],
                        ['a','concisenes'],
                        ['b','verb tense'],
                        ['c','inference'],
                        ['c','pronouns'],
                        ['c','placement'],
                        ['d','prepositions'],
                        ['b','transitions'],
                        ['c','transitions'],
                        ['b','possessives'],
                        ['c','inference'],
                        ['a','verb tense'],
                        ['a','conciseness'],
                        ['b','conciseness'],
                        ['c','inference'],
                        ['d','inference'],
                        ['a','inference'],
                        ['c','possessives'],
                        ['a','verb tense'],
                        ['a','inference'],
                        ['c','conciseness'],
                        ['b','yes/no'],
                        ['a','conciseness'],
                        ['c','possessives'],
                        ['b','verb tense'],
                        ['a','conciseness'],
                        ['d','inference'],
                        ['b','inference'],
                        ['c','pronouns'],
                        ['d','conciseness'],
                        ['c','adjectives/adverbs'],
                        ['a','conciseness'],
                        ['d','punctuation'],
                        ['c','transitions'],
                        ['b','inference'],
                        ['d','omit/delete'],
                        ['b','punctuation'],
                        ['d','inference'],
                        ['c','modifying clauses'],
                        ['b','verb tense'],
                        ['a','possessives'],
                        ['b','conciseness'],
                        ['d','conciseness'],
                        ['d','conciseness'],
                        ['a','conciseness'],
                        ['d','pronouns'],
                        ['c','inference'],
                        ['b','vocab in context'],
                        ['a','omit/delete'],
                        ['d','inference'],
                        ['c','inference'],
                        ['a','yes/no'],
                        ['b','inference'],
                        ['b','possessives'],
                        ['c','placement'],
                        ['d','inference'],
                        ['d','modifying clauses'],
                        ['a','transitions'],
                        ['c','verb tense'],
                        ['b','inference'],
                        ['a','inference'],
                        ['d','yes/no'],
                        ['b','conciseness'],
                        ['b','omit/delete'],
                        ['c','punctuation'],
                        ['d','adjectives/adverbs'],
                        ['d','punctuation'],
                        ['a','inference'],
                        ['b','passive voice'],
                        ['b','yes/no'],
                        ['d','conciseness'],
                        ['c','comparisons'],
                        ['a','punctuation'],
                        ['d','pronouns'],
                        ['c','yes/no']
                    ]
    },
    math: {
        scorescale: [
                        1, 4, 6, 8, 10, 11, 11, 12, 13, 13, 13, 14, 14, 15, 15, 15, 15,
                        16, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 20, 20, 21, 21,
                        22, 22, 23, 23, 23, 24, 24, 24, 25, 25, 26, 26, 26, 27, 27, 28,
                        28, 28, 29, 30, 30, 31, 32, 33, 34, 34, 35, 36
                    ],
        questions: [
                        ['d', '1-20'],
                        ['b', '1-20'],
                        ['c', '1-20'],
                        ['a', '1-20'],
                        ['a', '1-20'],
                        ['d', '1-20'],
                        ['c', '1-20'],
                        ['d', '1-20'],
                        ['b', '1-20'],
                        ['b', '1-20'],
                        ['b', '1-20'],
                        ['a', '1-20'],
                        ['d', '1-20'],
                        ['d', '1-20'],
                        ['d', '1-20'],
                        ['e', '1-20'],
                        ['b', '1-20'],
                        ['b', '1-20'],
                        ['c', '1-20'],
                        ['e', '1-20'],
                        ['e', '21-40'],
                        ['c', '21-40'],
                        ['b', '21-40'],
                        ['a', '21-40'],
                        ['c', '21-40'],
                        ['c', '21-40'],
                        ['b', '21-40'],
                        ['b', '21-40'],
                        ['e', '21-40'],
                        ['d', '21-40'],
                        ['c', '21-40'],
                        ['d', '21-40'],
                        ['e', '21-40'],
                        ['c', '21-40'],
                        ['c', '21-40'],
                        ['e', '21-40'],
                        ['b', '21-40'],
                        ['b', '21-40'],
                        ['e', '21-40'],
                        ['d', '21-40'],
                        ['e', '41-60'],
                        ['d', '41-60'],
                        ['a', '41-60'],
                        ['a', '41-60'],
                        ['e', '41-60'],
                        ['e', '41-60'],
                        ['d', '41-60'],
                        ['c', '41-60'],
                        ['e', '41-60'],
                        ['c', '41-60'],
                        ['b', '41-60'],
                        ['a', '41-60'],
                        ['d', '41-60'],
                        ['a', '41-60'],
                        ['d', '41-60'],
                        ['a', '41-60'],
                        ['a', '41-60'],
                        ['e', '41-60'],
                        ['c', '41-60'],
                        ['a', '41-60']
                    ]
    },
    reading: {
        scorescale: [
                        1, 2, 4, 5, 7, 8, 9, 10, 11, 11, 12, 13, 13, 14, 15, 15, 16, 16,
                        17, 18, 18, 19, 20, 20, 21, 22, 22, 23, 23, 24, 25, 26, 27, 28,
                        29, 30, 31, 32, 33, 34, 36
                    ],
        questions: [
                        ['b' , 'big picture'],
                        ['c' , 'detail'],
                        ['a' , 'detail'],
                        ['d' , 'inference'],
                        ['c' , 'purpose'],
                        ['d' , 'vocab in context'],
                        ['b' , 'detail'],
                        ['c' , 'detail'],
                        ['b' , 'inference'],
                        ['b' , 'detail'],
                        ['a' , 'big picture'],
                        ['d' , 'detail'],
                        ['c' , 'detail'],
                        ['d' , 'purpose'],
                        ['c' , 'purpose'],
                        ['c' , 'vocab in context'],
                        ['b' , 'detail'],
                        ['a' , 'inference'],
                        ['d' , 'detail'],
                        ['a' , 'inference'],
                        ['c' , 'big picture'],
                        ['a' , 'purpose'],
                        ['c' , 'inference'],
                        ['b' , 'detail'],
                        ['d' , 'detail'],
                        ['d' , 'vocab in context'],
                        ['b' , 'detail'],
                        ['a' , 'detail'],
                        ['c' , 'detail'],
                        ['a' , 'detail'],
                        ['b' , 'inference'],
                        ['d' , 'detail'],
                        ['d' , 'detail'],
                        ['d' , 'detail'],
                        ['b' , 'inference'],
                        ['d' , 'detail'],
                        ['a' , 'vocab in context'],
                        ['c' , 'detail'],
                        ['b' , 'detail'],
                        ['c' , 'detail']
                    ]
    },
    science: {
        scorescale: [
                        1, 3, 4, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 17, 18,
                        19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 27,  
                        27, 28, 30, 31, 32, 34, 36
                    ],
        questions: [
                        ['d' , 'detail'],
                        ['b' , 'trend'],
                        ['d' , 'outside information'],
                        ['c' , 'trend'],
                        ['b' , 'detail'],
                        ['d' , 'detail'],
                        ['c' , 'trend'],
                        ['b' , 'new information'],
                        ['a' , 'detail'],
                        ['c' , 'inference'],
                        ['a' , 'inference'],
                        ['a' , 'detail'],
                        ['c' , 'detail'],
                        ['a' , 'detail'],
                        ['a' , 'detail'],
                        ['d' , 'detail'],
                        ['b' , 'detail'],
                        ['d' , 'new information'],
                        ['c' , 'detail'],
                        ['c' , 'detail'],
                        ['a' , 'trend'],
                        ['d' , 'new information'],
                        ['b' , 'method'],
                        ['b' , 'new information'],
                        ['b' , 'detail'],
                        ['c' , 'detail'],
                        ['a' , 'new information'],
                        ['a' , 'new information'],
                        ['d' , 'trend'],
                        ['c' , 'detail'],
                        ['a' , 'detail'],
                        ['b' , 'new information'],
                        ['d' , 'trend'],
                        ['b' , 'method'],
                        ['d' , 'detail'],
                        ['c' , 'detail'],
                        ['b' , 'trend'],
                        ['d' , 'detail'],
                        ['c' , 'new information'],
                        ['d' , 'detail']
                    ]
    },
}

const a09 = {
    id: 'a09',
    english:{
        scorescale: [
                        1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, 10, 10, 10,
                        11, 11, 11, 12, 12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 15, 16,
                        16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 22, 22, 22, 
                        23, 23, 23, 24, 24, 24, 25, 25, 25, 26, 27, 27, 28, 29, 30, 30, 
                        31, 33, 34, 35, 35, 35, 36, 36
                    ],
        questions: [
                        ['c' , 'punctuation'],
                        ['a' , 'punctuation'],
                        ['b' , 'yes/no'],
                        ['b' , 'possessives'],
                        ['b' , 'transitions'],
                        ['c' , 'punctuation'],
                        ['a' , 'vocab in context'],
                        ['d' , 'conciseness'],
                        ['a' , 'inference'],
                        ['c' , 'prepositions'],
                        ['d' , 'placement'],
                        ['c' , 'vocab in context'],
                        ['b' , 'inference'],
                        ['d' , 'punctuation'],
                        ['c' , 'prepositions'],
                        ['a' , 'punctuation'],
                        ['b' , 'inference'],
                        ['d' , 'verb tense'],
                        ['c' , 'parallelism'],
                        ['d' , 'omit/delete'],
                        ['b' , 'inference'],
                        ['d' , 'conciseness'],
                        ['a' , 'punctuation'],
                        ['b' , 'vocab in context'],
                        ['b' , 'vagueness'],
                        ['b' , 'conciseness'],
                        ['c' , 'inference'],
                        ['d' , 'placement'],
                        ['a' , 'inference'],
                        ['d' , 'verb tense'],
                        ['d' , 'inference'],
                        ['b' , 'punctuation'],
                        ['a' , 'punctuation'],
                        ['c' , 'vocab in context'],
                        ['c' , 'adjectives / adverbs'],
                        ['b' , 'conciseness'],
                        ['c' , 'vocab in context'],
                        ['a' , 'transitions'],
                        ['c' , 'inference'],
                        ['a' , 'conciseness'],
                        ['b' , 'omit/delete'],
                        ['d' , 'inference'],
                        ['d' , 'conciseness'],
                        ['a' , 'punctuation'],
                        ['c' , 'yes/no'],
                        ['b' , 'vocab in context'],
                        ['a' , 'comparisons'],
                        ['a' , 'prepositions'],
                        ['d' , 'conciseness'],
                        ['d' , 'conciseness'],
                        ['b' , 'parallelism'],
                        ['d' , 'omit/delete'],
                        ['c' , 'conciseness'],
                        ['a' , 'inference'],
                        ['b' , 'inference'],
                        ['a' , 'vagueness'],
                        ['c' , 'transitions'],
                        ['d' , 'possessives'],
                        ['c' , 'inference'],
                        ['c' , 'yes/no'],
                        ['b' , 'inference'],
                        ['c' , 'vocab in contex'],
                        ['c' , 'prepositions'],
                        ['d' , 'conciseness'],
                        ['d' , 'inference'],
                        ['c' , 'parallelism'],
                        ['a' , 'conciseness'],
                        ['d' , 'pronouns'],
                        ['c' , 'conciseness'],
                        ['a' , 'punctuation'],
                        ['a' , 'conciseness'],
                        ['d' , 'inference'],
                        ['a' , 'contractions'],
                        ['b' , 'punctuation'],
                        ['b' , 'yes/no'],
                    ]
    },
    math: {
        scorescale: [
                        1, 5, 7, 9, 11, 12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
                        17, 17, 17, 18, 18, 18, 19, 19, 20, 20, 21, 22, 22, 23, 23, 24, 24,
                        24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 28, 28, 28, 29, 29, 30, 31, 
                        31, 32, 33, 33, 34, 35, 35, 36, 36
                    ],
        questions: [
                        ['a', '1-20'],
                        ['d', '1-20'],
                        ['c', '1-20'],
                        ['e', '1-20'],
                        ['c', '1-20'],
                        ['c', '1-20'],
                        ['a', '1-20'],
                        ['b', '1-20'],
                        ['e', '1-20'],
                        ['b', '1-20'],
                        ['d', '1-20'],
                        ['b', '1-20'],
                        ['b', '1-20'],
                        ['d', '1-20'],
                        ['e', '1-20'],
                        ['e', '1-20'],
                        ['e', '1-20'],
                        ['d', '1-20'],
                        ['a', '1-20'],
                        ['b', '1-20'],
                        ['a', '21-40'],  
                        ['d', '21-40'],   
                        ['a', '21-40'],
                        ['b', '21-40'],   
                        ['c', '21-40'],
                        ['c', '21-40'],  
                        ['c', '21-40'],   
                        ['c', '21-40'],
                        ['d', '21-40'],   
                        ['b', '21-40'],
                        ['d', '21-40'],  
                        ['c', '21-40'],   
                        ['a', '21-40'],
                        ['a', '21-40'],   
                        ['b', '21-40'],
                        ['b', '21-40'],  
                        ['e', '21-40'],   
                        ['d', '21-40'],
                        ['d', '21-40'],   
                        ['e', '21-40'],  
                        ['b', '41-60'],
                        ['a', '41-60'],
                        ['c', '41-60'],
                        ['a', '41-60'],
                        ['a', '41-60'],   
                        ['c', '41-60'],
                        ['b', '41-60'],
                        ['e', '41-60'],
                        ['e', '41-60'],
                        ['c', '41-60'],
                        ['d', '41-60'],
                        ['d', '41-60'],
                        ['b', '41-60'],
                        ['d', '41-60'],
                        ['d', '41-60'],
                        ['a', '41-60'],
                        ['a', '41-60'],
                        ['a', '41-60'],
                        ['e', '41-60'],
                        ['e', '41-60']   
                    ]
    },
    reading: {
        scorescale: [
                        1, 2, 4, 5, 6, 8, 9, 10, 10, 11, 12, 12, 13, 14, 14, 15, 16, 17, 17,
                        18, 19, 19, 20, 21, 22, 22, 23, 24, 24, 25, 26, 28, 29, 30, 31, 32,
                        33, 34, 35, 36, 36
                    ],
        questions: [
                        ['d' , 'detail'],
                        ['c' , 'purpose'],
                        ['b' , 'inference'],
                        ['c' , 'inference'],
                        ['a' , 'inference'],
                        ['d' , 'detail'],
                        ['b' , 'vocab in context'],
                        ['d' , 'detail'],
                        ['d' , 'purpose'],
                        ['c' , 'detail'],
                        ['c' , 'big picture'],
                        ['b' , 'purpose'],
                        ['c' , 'inference'],
                        ['d' , 'inference'],
                        ['b' , 'detail'],
                        ['a' , 'detail'],
                        ['c' , 'detail'],
                        ['b' , 'vocab in context'],
                        ['d' , 'inference'],
                        ['a' , 'detail'],
                        ['c' , 'purpose'],
                        ['c' , 'inference'],
                        ['d' , 'vocab in context'],
                        ['a' , 'inference'],
                        ['d' , 'inference'],
                        ['a' , 'inference'],
                        ['c' , 'vocab in context'],
                        ['b' , 'big picture'],
                        ['a' , 'big picture'],
                        ['b' , 'big picture'],
                        ['d' , 'big picture'],
                        ['a' , 'inference'],
                        ['b' , 'inference'],
                        ['b' , 'detail'],
                        ['c' , 'detail'],
                        ['d' , 'detail'],
                        ['a' , 'detail'],
                        ['c' , 'inference'],
                        ['c' , 'vocab in context'],
                        ['b' , 'inference']
                    ]
    },
    science: {
        scorescale: [
                        1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 15, 16, 17, 17, 18, 18,
                        19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 26, 27, 28, 29, 30, 31,
                        33, 34, 35, 36
                    ],
        questions: [
                        ['c' , 'new information'],
                        ['a' , 'inference'],
                        ['b' , 'inference'],
                        ['d' , 'inference'],
                        ['c' , 'new information'],
                        ['c' , 'inference'],
                        ['a' , 'inference'],
                        ['a' , 'detail'],
                        ['a' , 'detail'],
                        ['c' , 'detail'],
                        ['d' , 'new information'],
                        ['a' , 'new information'],
                        ['b' , 'inference'],
                        ['b' , 'detail'],
                        ['c' , 'new information'],
                        ['d' , 'inference'],
                        ['c' , 'new information'],
                        ['b' , 'inference'],
                        ['c' , 'detail'],
                        ['d' , 'new information'],
                        ['a' , 'detail'],
                        ['a' , 'detail'],
                        ['d' , 'detail'],
                        ['b' , 'new information'],
                        ['d' , 'new information'],
                        ['a' , 'new information'],
                        ['c' , 'new information'],
                        ['c' , 'inference'],
                        ['a' , 'inference'],
                        ['d' , 'inference'],
                        ['b' , 'inference'],
                        ['d' , 'inference'],
                        ['a' , 'inference'],
                        ['b' , 'detail'],
                        ['a' , 'detail'],
                        ['c' , 'inference'],
                        ['d' , 'detail'],
                        ['b' , 'detail'],
                        ['d' , 'detail'],
                        ['d' , 'detail']
                    ]
    },
}

const b05 = {
    id: 'b05',
    english:{
        scorescale: [
            1, 1, 2, 3, 4, 4, 5, 5, 6, 7, 7, 8, 8, 8, 9, 9, 10, 10, 10,
            11, 11, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 15, 16, 16,
            17, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23,
            24, 24, 24, 25, 25, 26,26, 27, 28, 29, 30, 31, 32, 33, 34, 34, 35, 35, 35, 35,
            36, 36, 36,
        ],
        questions: [
                    ['a','parallelism'],
                    ['b','inference'],
                    ['d','verb tense'],
                    ['c','punctuation'],
                    ['a','conciseness'],
                    ['c','modifying clause'],
                    ['b','punctuation'],
                    ['b','ambiguity'],
                    ['a','conciseness'],
                    ['d','conciseness'],
                    ['c','conciseness'],
                    ['b','transitions'],
                    ['a','punctuation'],
                    ['b','inference'],
                    ['c','placement'],
                    ['b','subject/verb agreement'],
                    ['c','parallelism'],
                    ['b','pronouns'],
                    ['d','modifying clause'],
                    ['c','possessives'],
                    ['d','conciseness'],
                    ['a','punctuation'],
                    ['d','conciseness'],
                    ['a','conciseness'],
                    ['d','omit/delete'],
                    ['a','inference'],
                    ['a','omit/delete'],
                    ['c','inference'],
                    ['d','conciseness'],
                    ['a','conciseness'],
                    ['a','punctuation'],
                    ['b','vocab in context'],
                    ['c','inference'],
                    ['a','conciseness'],
                    ['d','conciseness'],
                    ['a','punctuation'],
                    ['c','punctuation'],
                    ['d','subject/verb agreement'],
                    ['d','omit/delete'],
                    ['b','parallelism'],
                    ['a','conciseness'],
                    ['d','transitions'],
                    ['b','placement'],
                    ['c','inference'],
                    ['b','placement'],
                    ['d','conciseness'],
                    ['d','transitions'],
                    ['b','omit/delete'],
                    ['a','conciseness'],
                    ['b','inference'],
                    ['c','omit/delete'],
                    ['a','punctuation'],
                    ['d','yes/no'],
                    ['b','conciseness'],
                    ['a','possessives'],
                    ['d','transitions'],
                    ['c','conciseness'],
                    ['d','verb tense'],
                    ['d','placement'],
                    ['c','yes/no'],
                    ['d','modifying clause'],
                    ['b','omit/delete'],
                    ['b','punctuation'],
                    ['d','conciseness'],
                    ['d','inference'],
                    ['b','pronouns'],
                    ['c','inference'],
                    ['c','punctuation'],
                    ['d','possessives'],
                    ['b','inference'],
                    ['a','transitions'],
                    ['c','placement'],
                    ['c','yes/no'],
                    ['b','punctuation'],
                    ['c','transitions']
                ]
    },
    math: {
        scorescale: [
                        1, 4, 6, 8, 9, 10, 11, 12, 12, 13, 13, 14, 14, 14, 14,
                        15, 15, 15, 16, 16, 16, 17, 17, 18, 18, 18, 19, 20, 20,
                        21, 22, 22, 23, 24, 24, 25, 25, 26, 26, 26, 27, 27, 28, 28, 28,
                        29, 29, 30, 30, 31, 31, 32, 33, 33, 34, 35, 35, 35, 36, 36
                    ],
        questions: [
                    ['d', '1-20'],
                    ['b', '1-20'],
                    ['d', '1-20'],
                    ['a', '1-20'],
                    ['c', '1-20'],
                    ['b', '1-20'],
                    ['c', '1-20'],
                    ['a', '1-20'],
                    ['e', '1-20'],
                    ['b', '1-20'],
                    ['b', '1-20'],
                    ['d', '1-20'],
                    ['a', '1-20'],
                    ['d', '1-20'],
                    ['d', '1-20'],
                    ['e', '1-20'],
                    ['c', '1-20'],
                    ['e', '1-20'],
                    ['c', '1-20'],
                    ['c', '1-20'],
                    ['e', '21-40'],
                    ['c', '21-40'],
                    ['e', '21-40'],
                    ['d', '21-40'],
                    ['b', '21-40'],
                    ['c', '21-40'],
                    ['e', '21-40'],
                    ['a', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['b', '21-40'],
                    ['a', '21-40'],
                    ['b', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['c', '21-40'],
                    ['d', '21-40'],
                    ['b', '21-40'],
                    ['e', '21-40'],
                    ['e', '21-40'],
                    ['b', '41-60'],
                    ['b', '41-60'],
                    ['d', '41-60'],
                    ['a', '41-60'],
                    ['b', '41-60'],
                    ['a', '41-60'],
                    ['d', '41-60'],
                    ['b', '41-60'],
                    ['a', '41-60'],
                    ['d', '41-60'],
                    ['b', '41-60'],
                    ['b', '41-60'],
                    ['a', '41-60'],
                    ['d', '41-60'],
                    ['a', '41-60'],
                    ['d', '41-60'],
                    ['c', '41-60'],
                    ['e', '41-60'],
                    ['a', '41-60'],
                    ['a', '41-60'],
                ]
    },
    reading: {
        scorescale: [
                        1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 13, 14, 15, 15, 16, 17, 17,
                        18, 19, 19, 20, 21, 21, 22, 23, 24, 24, 25, 26, 27,28, 30, 31, 32, 33, 34, 35,
                        36
        ],
        questions: [
                    ['b', 'inference'],
                    ['c', 'vocab in context'],
                    ['c', 'purpose'],
                    ['b', 'detail'],
                    ['a', 'inference'],
                    ['b', 'purpose'],
                    ['d', 'vocab in context'],
                    ['a', 'detail'],
                    ['a', 'detail'],
                    ['c', 'detail'],
                    ['b', 'inference'],
                    ['d', 'big picture'],
                    ['d', 'purpose'],
                    ['c', 'purpose'],
                    ['a', 'purpose'],
                    ['c', 'detail'],
                    ['b', 'vocab in context'],
                    ['d', 'detail'],
                    ['b', 'vocab in context'],
                    ['a', 'detail'],
                    ['b', 'vocab in context'],
                    ['d', 'inference'],
                    ['c', 'detail'],
                    ['b', 'purpose'],
                    ['c', 'big picture'],
                    ['a', 'detail'],
                    ['b', 'detail'],
                    ['c', 'big picture'],
                    ['d', 'inference'],
                    ['d', 'detail'],
                    ['c', 'big picture'],
                    ['a', 'purpose'],
                    ['b', 'detail'],
                    ['d', 'inference'],
                    ['c', 'inference'],
                    ['c', 'detail'],
                    ['a', 'inference'],
                    ['d', 'inference'],
                    ['c', 'detail'],
                    ['d', 'detail']
        ]
    },
    science: {
        scorescale: [
                        1, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 17, 18, 18,
                        19 ,19, 20, 21, 21, 22, 23, 24, 25, 25, 26, 27, 28, 29, 30,
                        31, 33, 34, 35, 36, 36 
        ],
        questions: [
                    ['b', 'detail'],
                    ['c', 'new information'],
                    ['c', 'new information'],
                    ['c', 'trend'],
                    ['d', 'outside information'],
                    ['a', 'new information'],
                    ['a', 'trend'],
                    ['b', 'new information'],
                    ['c', 'method'],
                    ['c', 'detail'],
                    ['b', 'detail'],
                    ['d', 'trend'],
                    ['d', 'trend'],
                    ['b', 'new information'],
                    ['c', 'method'],
                    ['a', 'new information'],
                    ['b', 'new information'],
                    ['a', 'trend'],
                    ['a', 'method'],
                    ['d', 'detail'],
                    ['a', 'detail'],
                    ['d', 'detail'],
                    ['c', 'detail'],
                    ['a', 'detail'],
                    ['d', 'detail'],
                    ['a', 'trend'],
                    ['b', 'trend'],
                    ['b', 'trend'],
                    ['d', 'detail'],
                    ['c', 'new information'],
                    ['a', 'detail'],
                    ['a', 'new information'],
                    ['c', 'detail'],
                    ['a', 'new information'],
                    ['a', 'detail'],
                    ['a', 'detail'],
                    ['c', 'detail'],
                    ['a', 'new information'],
                    ['d', 'outside information'],
                    ['d', 'trend']
        ]
    },
}

const z15 = {
    /**
     * Represents a test. Each test has an id,
     * an English, Math, Reading, and Science section.
     * Each section contains a score scale and an array
     * of questions. Questions indicate correct answers
     * and question type.
     */
    id: 'z15',
    english:{
        scorescale: [1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 13, 13, 14, 14, 
                    15, 15, 15, 15, 16, 16, 17, 17, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22,
                    23, 23, 23, 24, 24, 24, 25, 25, 26, 26, 27, 27, 28, 29, 29, 30, 31, 32, 33, 33, 34, 35, 35, 35, 36, 36],
        questions: [
                        ['d','modifying clauses'],
                        ['b','inference'],
                        ['a','punctuation'],
                        ['b','punctuation'],
                        ['d','conciseness'],
                        ['d','conciseness'],
                        ['b','comparisons'],
                        ['b','vocab in context'],
                        ['c','inference'],
                        ['c','prepositions'],
                        ['c','pronouns'],
                        ['c','inference'],
                        ['d','conciseness'],
                        ['a','yes/no'],
                        ['c','punctuation'],
                        ['b','concisness'],
                        ['a','comparisons'],
                        ['a','yes/no'],
                        ['d','conciseness'],
                        ['c','inference'],
                        ['b','parallelism'],
                        ['c','placement'],
                        ['d','conciseness'],
                        ['a','punctuation'],
                        ['b','punctuation'],
                        ['d','subject/verb agreement'],
                        ['a','vocab in context'],
                        ['c','punctuation'],
                        ['a','vocab in context'],
                        ['c','yes/no'],
                        ['b','punctuation'],
                        ['c','inference'],
                        ['b','punctuation'],
                        ['d','parallelism'],
                        ['d','prepositions'],
                        ['d','conciseness'],
                        ['a','conciseness'],
                        ['d','placement'],
                        ['c','omit/delete'],
                        ['c','inference'],
                        ['d','inference'],
                        ['b','inference'],
                        ['a','subject/verb agreement'],
                        ['d','omit/delete'],
                        ['c','placement'],
                        ['b','punctuation'],
                        ['c','pronouns'],
                        ['a','punctuation'],
                        ['d','punctuation'],
                        ['a','possessives'],
                        ['a','inference '],
                        ['c','punctuation'],
                        ['a','conciseness'],
                        ['d','conciseness'],
                        ['d','conciseness'],
                        ['b','transitons'],
                        ['a','punctuation'],
                        ['b','inference'],
                        ['d','verb tense'],
                        ['c','yes/no'],
                        ['d','parallelism'],
                        ['d','punctuation'],
                        ['d','transitions'],
                        ['c','pronouns'],
                        ['a','inference'],
                        ['b','punctuation'],
                        ['a','inference'],
                        ['c','inference'],
                        ['b','vocab in context'],
                        ['b','inference'],
                        ['c','placement'],
                        ['a','inference'],
                        ['c','prepositions'],
                        ['d','transitions'],
                        ['a','omit/delete'],
                ]
    },
    math: {
        scorescale: [
                        1, 4, 7, 8, 10, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 15,
                        16, 16 ,16 ,16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 
                        21, 21, 22, 22, 23, 23, 24, 24, 24, 25, 25, 26, 26, 26, 
                        27, 27, 27, 28, 28, 28, 29, 29, 30, 31, 32, 33, 34, 35,
                        35, 36, 36
        ],
        questions: [
                    ['a', '1-20'],
                    ['d', '1-20'],
                    ['b', '1-20'],
                    ['c', '1-20'],
                    ['c', '1-20'],
                    ['b', '1-20'],
                    ['a', '1-20'],
                    ['b', '1-20'],
                    ['a', '1-20'],
                    ['a', '1-20'],
                    ['b', '1-20'],
                    ['a', '1-20'],
                    ['a', '1-20'],
                    ['c', '1-20'],
                    ['a', '1-20'],
                    ['d', '1-20'],
                    ['e', '1-20'],
                    ['a', '1-20'],
                    ['e', '1-20'],
                    ['c', '1-20'],
                    ['e', '21-40'],
                    ['e', '21-40'],
                    ['d', '21-40'],
                    ['e', '21-40'],
                    ['c', '21-40'],
                    ['a', '21-40'],
                    ['b', '21-40'],
                    ['c', '21-40'],
                    ['d', '21-40'],
                    ['d', '21-40'],
                    ['e', '21-40'],
                    ['c', '21-40'],
                    ['e', '21-40'],
                    ['b', '21-40'],
                    ['c', '21-40'],
                    ['a', '21-40'],
                    ['d', '21-40'],
                    ['b', '21-40'],
                    ['e', '21-40'],
                    ['d', '21-40'],
                    ['e', '41-60'],
                    ['b', '41-60'],
                    ['c', '41-60'],
                    ['a', '41-60'],
                    ['a', '41-60'],
                    ['e', '41-60'],
                    ['d', '41-60'],
                    ['d', '41-60'],
                    ['d', '41-60'],
                    ['b', '41-60'],
                    ['b', '41-60'],
                    ['c', '41-60'],
                    ['c', '41-60'],
                    ['e', '41-60'],
                    ['a', '41-60'],
                    ['e', '41-60'],
                    ['d', '41-60'],
                    ['b', '41-60'],
                    ['c', '41-60'],
                    ['b', '41-60']
                ]
    },
    reading: {
        scorescale: [
            1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 15, 15, 16, 17, 17, 18, 19, 20, 20,
            21, 22, 22, 23, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36
        ],
        questions: [
                    ['c','big picture'],
                    ['c','inference'],
                    ['d','detail'],
                    ['a','inference'],
                    ['c','inference'],
                    ['d','detail'],
                    ['d','inference'],
                    ['b','detail'],
                    ['c','inference'],
                    ['d','inference'],
                    ['a','big picture'],
                    ['b','inference'],
                    ['d','inference'],
                    ['c','purpose'],
                    ['b','detail'],
                    ['a','inference'],
                    ['b','detail'],
                    ['a','detail'],
                    ['b','inference'],
                    ['c','detail'],
                    ['b','purpose'],
                    ['b','detail'],
                    ['c','vocab in context'],
                    ['c','inference'],
                    ['c','inference'],
                    ['b','detail'],
                    ['b','vocab in context'],
                    ['a','big picture'],
                    ['d','big picture'],
                    ['a','inference'],
                    ['b','big picture'],
                    ['b','purpose'],
                    ['d','detail'],
                    ['d','purpose'],
                    ['c','detail'],
                    ['a','detail'],
                    ['b','detail'],
                    ['c','detail'],
                    ['a','inference'],
                    ['a','inference']
        ]
    },
    science: {
        scorescale: [
            1, 3, 5, 6, 8, 9, 10, 11, 12, 13, 13, 14, 15, 16, 16, 17, 18, 18, 19, 20,
            20, 21, 21, 22, 22, 23, 24, 24, 25, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 36
        ],
        questions: [
                    ['d', 'detail'],
                    ['c', 'trend'],
                    ['a', 'method'],
                    ['b', 'detail'],
                    ['a', 'inference'],
                    ['c', 'new information'],
                    ['b', 'trend'],
                    ['b', 'new information'],
                    ['d', 'inference'],
                    ['d', 'detail'],
                    ['a', 'outside information'],
                    ['c', 'inference'],
                    ['a', 'outside information'],
                    ['b', 'method'],
                    ['c', 'new information'],
                    ['a', 'new information'],
                    ['d', 'detail'],
                    ['c', 'new information'],
                    ['b', 'detail'],
                    ['d', 'new information'],
                    ['a', 'trend'],
                    ['c', 'detail'],
                    ['d', 'new information'],
                    ['d', 'detail'],
                    ['d', 'new information'],
                    ['c', 'new information'],
                    ['a', 'new information'],
                    ['d', 'trend'],
                    ['b', 'new information'],
                    ['c', 'detail'],
                    ['c', 'trend'],
                    ['d', 'detail'],
                    ['a', 'new information'],
                    ['a', 'method'],
                    ['b', 'detail'],
                    ['a', 'detail'],
                    ['c', 'outside information'],
                    ['a', 'detail'],
                    ['d', 'detail'],
                    ['b', 'detail'],
        ]
    },
}

export default {
    a11,
    e73,
    a09,
    f67,
    z15,
    b05
}