const a11 = {
    /**
     * Represents a test. Each test has an id,
     * an English, Math, Reading, and Science section.
     * Each section contains a score scale and an array
     * of questions. Questions indicate correct answers
     * and question type.
     */
    id: 'a11',
    english:{
        scorescale: [1, 1, 2, 3, 3, 4, 5, 5, 
                    6, 6, 7, 7, 8, 8, 9, 9, 9, 
                    10, 10, 10, 11, 11, 11, 12, 
                    12, 13, 13, 14, 14, 14, 15, 
                    15, 15, 15, 16, 16, 16, 17, 
                    17, 17, 18, 19, 19, 20, 20, 
                    20, 21, 21, 21, 22, 22, 22, 
                    23, 23, 23, 24, 24, 25, 25, 
                    25, 26, 27, 27, 28, 29, 30, 
                    31, 32, 33, 34, 34, 35, 35, 
                    36, 36, 36],
        questions: [['C', 'verb tense'],
                    ['C', 'inference'],
                    ['D', 'conciseness'],
                    ['B', 'omit/delete'],
                    ['D', 'conciseness'],
                    ['D', 'verb tense'],
                    ['B', 'transitions'],
                    ['C', 'punctuation'],
                    ['C', 'verb tense'],
                    ['A', 'verb tense'],
                    ['A', 'punctuation'],
                    ['D', 'placement'],
                    ['D', 'conciseness'],
                    ['C', 'yes/no'],
                    ['B', 'placement'],
                    ['D', 'omit/delete'],
                    ['A', 'conciseness'],
                    ['B', 'punctuation'],
                    ['A', 'prepositions'],
                    ['C', 'verb tense'],
                    ['A', 'punctuation'],
                    ['D', 'verb tense'],
                    ['C', 'prepositions'],
                    ['A', 'passive voice'],
                    ['B', 'inference'],
                    ['D', 'placement'],
                    ['D', 'prepositions'],
                    ['C', 'punctuation'],
                    ['B', 'placement'],
                    ['B', 'yes/no'],
                    ['A', 'conciseness'],
                    ['C', 'transitions'],
                    ['C', 'punctuation'],
                    ['D', 'inference'],
                    ['D', 'conciseness'],
                    ['A', 'inference'],
                    ['A', 'pronouns'],
                    ['A', 'punctuation'],
                    ['D', 'placement'],
                    ['B', 'yes/no'],
                    ['C', 'passive voice'],
                    ['C', 'inference'],
                    ['B', 'transitions'],
                    ['C', 'vocab in context'],
                    ['A', 'inference'],
                    ['B', 'inference'],
                    ['A', 'inference'],
                    ['D', 'punctuation'],
                    ['D', 'verb tense'],
                    ['C', 'pronouns'],
                    ['B', 'ambiguity / vagueness'],
                    ['D', 'inference'],
                    ['B', 'conciseness'],
                    ['A', 'conciseness'],
                    ['B', 'punctuation'],
                    ['A', 'inference'],
                    ['C', 'yes/no'],
                    ['C', 'conciseness'],
                    ['D', 'placement'],
                    ['B', 'yes/no'],
                    ['B', 'conciseness'],
                    ['A', 'conciseness'],
                    ['A', 'possessives'],
                    ['C', 'inference'],
                    ['A', 'inference'],
                    ['A', 'inference'],
                    ['C', 'punctuation'],
                    ['D', 'vocab in context'],
                    ['B', 'punctuation'],
                    ['B', 'vocab in context'],
                    ['D', 'modifying clauses'],
                    ['D', 'possessives'],
                    ['A', 'conciseness'],
                    ['C', 'inference'],
                    ['C', 'yes/no']]
    },
    math: {
        scorescale: [1, 4, 7, 9, 
                    10, 11, 12, 13, 
                    13, 14, 14, 14, 
                    15, 15, 15, 16, 
                    16, 16, 16, 17,
                    17, 17, 18, 18, 
                    19, 19, 19, 20, 
                    20, 21, 22, 22, 
                    23, 23, 24, 24, 
                    25, 25, 25, 26, 
                    26, 26, 27, 27, 27, 
                    28, 28, 28, 29, 29, 
                    30, 30, 31, 32, 33, 
                    33, 34, 35, 35, 36, 36],
        questions: [['D', '1-20'],
                    ['C', '1-20'],
                    ['C', '1-20'],
                    ['D', '1-20'],
                    ['A', '1-20'],
                    ['C', '1-20'],
                    ['D', '1-20'],
                    ['C', '1-20'],
                    ['B', '1-20'],
                    ['B', '1-20'],
                    ['A', '1-20'],
                    ['B', '1-20'],
                    ['C', '1-20'],
                    ['A', '1-20'],
                    ['C', '1-20'],
                    ['E', '1-20'],
                    ['A', '1-20'],
                    ['E', '1-20'],
                    ['A', '1-20'],
                    ['B', '1-20'],
                    ['D', '21-40'],
                    ['D', '21-40'],
                    ['E', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['D', '21-40'],
                    ['D', '21-40'],
                    ['B', '21-40'],
                    ['E', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['B', '21-40'],
                    ['E', '21-40'],
                    ['E', '21-40'],
                    ['B', '21-40'],
                    ['C', '21-40'],
                    ['A', '21-40'],
                    ['A', '21-40'],
                    ['E', '21-40'],
                    ['E', '41-60'],
                    ['A', '41-60'],
                    ['A', '41-60'],
                    ['D', '41-60'],
                    ['D', '41-60'],
                    ['E', '41-60'],
                    ['A', '41-60'],
                    ['E', '41-60'],
                    ['D', '41-60'],
                    ['B', '41-60'],
                    ['D', '41-60'],
                    ['C', '41-60'],
                    ['B', '41-60'],
                    ['B', '41-60'],
                    ['D', '41-60'],
                    ['E', '41-60'],
                    ['B', '41-60'],
                    ['A', '41-60'],
                    ['D', '41-60'],
                    ['B', '41-60']]
    },
    reading: {
        scorescale: [1, 2, 4, 5, 7, 8, 9, 10, 
                    11, 12, 12, 13, 13, 14, 15, 
                    15, 16, 17, 17, 18, 19, 20, 
                    20, 21, 22, 22, 23, 24, 25, 
                    26, 27, 28, 29, 30, 31, 32, 
                    33, 34, 35, 35, 36 ],
        questions: [['B', 'inference'],
                    ['A', 'inference'],
                    ['D', 'inference'],
                    ['D', 'inference'],
                    ['B', 'detail'],
                    ['C', 'purpose'],
                    ['A', 'inference'],
                    ['D', 'detail'],
                    ['D', 'detail'],
                    ['C', 'inference'],
                    ['D', 'purpose'],
                    ['D', 'inference'],
                    ['D', 'inference'],
                    ['C', 'inference'],
                    ['B', 'purpose'],
                    ['C', 'detail'],
                    ['C', 'inference'],
                    ['D', 'big picture'],
                    ['C', 'inference'],
                    ['A', 'big picture'],
                    ['D', 'inference'],
                    ['C', 'detail'],
                    ['A', 'detail'],
                    ['A', 'inference'],
                    ['B', 'vocab in context'],
                    ['D', 'inference'],
                    ['A', 'detail'],
                    ['B', 'inference'],
                    ['C', 'detail'],
                    ['C', 'detail'],
                    ['B', 'big picture'],
                    ['A', 'inference'],
                    ['D', 'detail'],
                    ['B', 'inference'],
                    ['C', 'detail'],
                    ['A', 'purpose'],
                    ['A', 'detail'],
                    ['C', 'inference'],
                    ['A', 'purpose'],
                    ['B', 'vocab in context']]
    },
    science: {
        scorescale: [1, 3, 5, 6, 8, 9, 
                    10, 11, 12, 13, 14, 
                    14, 15, 16, 17, 17, 
                    18, 19, 19, 20, 21, 
                    21, 22, 22, 23, 24, 
                    24, 25, 25, 26, 27, 
                    28, 29, 30, 31, 32, 
                    33, 34, 35, 36, 36],
        questions: [['B', 'detail'],
                    ['D', 'detail'],
                    ['A', 'detail'],
                    ['C', 'trend'],
                    ['A', 'trend'],
                    ['C', 'new information'],
                    ['D', 'detail'],
                    ['D', 'detail'],
                    ['C', 'detail'],
                    ['C', 'detail'],
                    ['D', 'method'],
                    ['A', 'detail'],
                    ['B', 'detail'],
                    ['C', 'detail'],
                    ['B', 'detail'],
                    ['B', 'detail'],
                    ['C', 'trend'],
                    ['D', 'new information'],
                    ['A', 'new information'],
                    ['A', 'trend'],
                    ['C', 'trend'],
                    ['A', 'trend'],
                    ['D', 'detail'],
                    ['A', 'new information'],
                    ['B', 'detail'],
                    ['B', 'outside information'],
                    ['C', 'method'],
                    ['A', 'detail'],
                    ['B', 'new information'],
                    ['B', 'new information'],
                    ['A', 'new information'],
                    ['C', 'new information'],
                    ['D', 'new information'],
                    ['D', 'detail'],
                    ['C', 'detail'],
                    ['C', 'new information'],
                    ['B', 'detail'],
                    ['B', 'method'],
                    ['C', 'trend'],
                    ['D', 'trend']]
    },
}

const e73 = {
    id: '73e',
    english:{
        scorescale: [
                        1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 7, 8, 8, 9, 9, 10, 10, 10,
                        11, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 16, 16, 16, 17,
                        17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23,
                        24, 24, 24, 25, 25, 25, 26, 26, 27, 27, 28, 29, 29, 30, 31, 32, 33,
                        34, 34, 35, 35, 36, 36
                    ],
        questions: [['D', 'punctuation'],
                    ['D', 'possessives'],
                    ['B', 'pronouns'],
                    ['A', 'inference'],
                    ['C', 'inference'],
                    ['C', 'pronouns'],
                    ['A', 'vocab in context'],
                    ['C', 'conciseness'],
                    ['C', 'omit/delete'],
                    ['A', 'prepositions'],
                    ['D', 'omit/delete'],
                    ['D', 'conciseness'],
                    ['B', 'punctuation'],
                    ['D', 'placement'],
                    ['C', 'yes/no'],
                    ['D', 'transitions'],
                    ['A', 'inference'],
                    ['B', 'punctuation'],
                    ['A', 'inference'],
                    ['C', 'transitions'],
                    ['D', 'pronouns'],
                    ['C', 'verb tense'],
                    ['A', 'punctuation'],
                    ['C', 'punctuation'],
                    ['D', 'conciseness'],
                    ['B', 'placement'],
                    ['A', 'punctuation'],
                    ['A', 'punctuation'],
                    ['B', 'inference'],
                    ['B', 'placement'],
                    ['A', 'punctuation'],
                    ['C', 'punctuation'],
                    ['A', 'subject/verb agreement'],
                    ['B', 'punctuation'],
                    ['C', 'yes/no'],
                    ['B', 'inference'],
                    ['D', 'inference'],
                    ['A', 'vocab in context'],
                    ['B', 'inference'],
                    ['C', 'verb tense'],
                    ['D', 'adjectives / adverbs'],
                    ['B', 'transitions'],
                    ['A', 'verb tense'],
                    ['B', 'inference'],
                    ['C', 'punctuation'], 
                    ['D', 'conciseness'],
                    ['B', 'possessives'],
                    ['A', 'punctuation'],
                    ['D', 'conciseness'],
                    ['D', 'conciseness'],
                    ['B', 'yes/no'],
                    ['D', 'punctuation'],
                    ['C', 'yes/no'],
                    ['B', 'subject/verb agreement'],
                    ['D', 'conciseness'],
                    ['A', 'parallelism'],
                    ['B', 'inference'],
                    ['B', 'omit/delete'],
                    ['A', 'inference'],
                    ['B', 'placement'],
                    ['D', 'conciseness'],
                    ['B', 'vocab in context'],
                    ['D', 'transitions'],
                    ['C', 'placement'],
                    ['B', 'punctuation'],
                    ['B', 'transitions'],
                    ['C', 'conciseness'],
                    ['A', 'ambiguity / vagueness'],
                    ['B', 'inference'],
                    ['C', 'transitions'],
                    ['A', 'comparisons'],
                    ['C', 'punctuation'],
                    ['D', 'punctuation'],
                    ['D', 'adjectives / adverbs'],
                    ['B', 'inference']]
    },
    math: {
        scorescale: [
                        1, 3, 5, 7, 9, 10, 11, 11, 12, 13, 13, 13, 14, 14,
                        15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 18, 18,
                        18, 19, 19, 20, 21, 21, 22, 22, 23, 23, 24, 24, 24,
                        25, 25, 26, 26, 26, 27, 27, 27, 28, 28, 29, 29, 30,
                        31, 32, 33, 33, 34, 35, 36, 36
                    ],
        questions: [['C', '1-20'],
                    ['D', '1-20'],
                    ['A', '1-20'],
                    ['A', '1-20'],
                    ['C', '1-20'],
                    ['E', '1-20'],
                    ['A', '1-20'],
                    ['B', '1-20'],
                    ['E', '1-20'],
                    ['D', '1-20'],
                    ['B', '1-20'],
                    ['D', '1-20'],
                    ['B', '1-20'],
                    ['B', '1-20'],
                    ['E', '1-20'],
                    ['D', '1-20'],
                    ['E', '1-20'],
                    ['B', '1-20'],
                    ['A', '1-20'],
                    ['C', '1-20'],
                    ['D', '21-40'],
                    ['D', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['B', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['A', '21-40'],
                    ['A', '21-40'],
                    ['E', '21-40'],
                    ['E', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['A', '21-40'],
                    ['E', '21-40'],
                    ['A', '21-40'],
                    ['B', '21-40'],
                    ['E', '21-40'],
                    ['B', '41-60'],
                    ['D', '41-60'],
                    ['A', '41-60'],
                    ['C', '41-60'],
                    ['A', '41-60'],
                    ['E', '41-60'],
                    ['D', '41-60'],
                    ['D', '41-60'],
                    ['A', '41-60'],
                    ['B', '41-60'],
                    ['D', '41-60'],
                    ['B', '41-60'],
                    ['D', '41-60'],
                    ['E', '41-60'],
                    ['C', '41-60'],
                    ['B', '41-60'],
                    ['B', '41-60'],
                    ['E', '41-60'],
                    ['D', '41-60'],
                    ['D', '41-60']]
    },
    reading: {
        scorescale: [
                        1, 2, 4, 5, 7, 8, 9, 10, 11, 12, 12, 13, 13, 
                        14, 15, 16, 16, 17, 18, 19, 19, 20, 21, 21,
                        22, 22, 23, 24, 24, 25, 26, 27, 28, 29, 30,
                        31, 32, 33, 34, 35, 36
                    ],
        questions: [['B', 'inference'],
        ['A', 'inference'],
        ['D', 'detail'],
        ['A', 'inference'],
        ['D', 'detail'],
        ['B', 'inference'],
        ['C', 'detail'],
        ['D', 'detail'],
        ['B', 'detail'],
        ['C', 'detail'],
        ['C', 'purpose'],
        ['B', 'big picture'],
        ['B', 'big picture'],
        ['B', 'detail'],
        ['D', 'purpose'],
        ['C', 'detail'],
        ['D', 'detail'],
        ['D', 'detail'],
        ['A', 'detail'],
        ['A', 'vocab in context'],
        ['D', 'purpose'],
        ['B', 'inference'],
        ['B', 'detail'],
        ['D', 'purpose'],
        ['C', 'inference'],
        ['B', 'purpose'],
        ['A', 'detail'],
        ['A', 'big picture'],
        ['A', 'inference'],
        ['D', 'purpose'],
        ['A', 'detail'],
        ['C', 'purpose'],
        ['D', 'purpose'],
        ['B', 'detail'],
        ['C', 'detail'],
        ['D', 'detail'],
        ['B', 'inference'],
        ['C', 'detail'],
        ['A', 'detail'],
        ['A', 'detail']]
    },
    science: {
        scorescale: [
                        1, 3, 5, 7, 8, 9, 10, 12, 12, 13, 14, 15, 16, 16, 
                        17, 18, 18, 19, 20, 20, 21, 22, 22, 23, 23, 24, 24,
                        25, 25, 26, 27, 28, 29, 30, 31, 33, 34, 35, 35, 36, 36
                    ],
        questions: [['C', 'detail'],
                    ['D', 'detail'],
                    ['A', 'detail'],
                    ['C', 'detail'],
                    ['B', 'detail'],
                    ['B', 'trend'],
                    ['C', 'inference'],
                    ['A', 'new information'],
                    ['A', 'detail'],
                    ['A', 'detail'],
                    ['C', 'inference'],
                    ['D', 'new information'],
                    ['C', 'inference'],
                    ['B', 'inference'],
                    ['A', 'new information'],
                    ['D', 'detail'],
                    ['D', 'detail'],
                    ['D', 'detail'],
                    ['A', 'outside information'],
                    ['B', 'inference'],
                    ['B', 'new information'],
                    ['C', 'detail'],
                    ['C', 'inference'],
                    ['D', 'detail'],
                    ['A', 'detail'],
                    ['D', 'new information'],
                    ['A', 'detail'],
                    ['B', 'new information'],
                    ['B', 'detail'],
                    ['B', 'detail'],
                    ['C', 'new information'],
                    ['D', 'inference'],
                    ['D', 'inference'],
                    ['C', 'inference'],
                    ['A', 'detail'],
                    ['B', 'new information'],
                    ['D', 'inference'],
                    ['D', 'detail'],
                    ['B', 'outside information'],
                    ['A', 'detail']]
    },
}

const f67 = {
    id: '67f',
    english:{
        scorescale: [
                        1, 1, 1, 2, 3, 3, 4, 4, 5, 5, 5, 6, 6, 7, 7, 7, 8, 8, 8, 8,
                        9, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 14, 14, 14, 15, 15,
                        16, 16, 16, 17, 17, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21,
                        21, 21, 22, 22, 23, 23, 23, 24, 24, 25, 25, 26, 26, 27, 27,
                        28, 29, 29, 30, 31, 32, 33, 34, 35, 36
                    ],
        questions: [
                        ['D','punctuation'],
                        ['A','concisenes'],
                        ['B','verb tense'],
                        ['C','inference'],
                        ['C','pronouns'],
                        ['C','placement'],
                        ['D','prepositions'],
                        ['B','transitions'],
                        ['C','transitions'],
                        ['B','possessives'],
                        ['C','inference'],
                        ['A','verb tense'],
                        ['A','conciseness'],
                        ['B','conciseness'],
                        ['C','inference'],
                        ['D','inference'],
                        ['A','inference'],
                        ['C','possessives'],
                        ['A','verb tense'],
                        ['A','inference'],
                        ['C','conciseness'],
                        ['B','yes/no'],
                        ['A','conciseness'],
                        ['C','possessives'],
                        ['B','verb tense'],
                        ['A','conciseness'],
                        ['D','inference'],
                        ['B','inference'],
                        ['C','pronouns'],
                        ['D','conciseness'],
                        ['C','adjectives/adverbs'],
                        ['A','conciseness'],
                        ['D','punctuation'],
                        ['C','transitions'],
                        ['B','inference'],
                        ['D','omit/delete'],
                        ['B','punctuation'],
                        ['D','inference'],
                        ['C','modifying clauses'],
                        ['B','verb tense'],
                        ['A','possessives'],
                        ['B','conciseness'],
                        ['D','conciseness'],
                        ['D','conciseness'],
                        ['A','conciseness'],
                        ['D','pronouns'],
                        ['C','inference'],
                        ['B','vocab in context'],
                        ['A','omit/delete'],
                        ['D','inference'],
                        ['C','inference'],
                        ['A','yes/no'],
                        ['B','inference'],
                        ['B','possessives'],
                        ['C','placement'],
                        ['D','inference'],
                        ['D','modifying clauses'],
                        ['A','transitions'],
                        ['C','verb tense'],
                        ['B','inference'],
                        ['A','inference'],
                        ['D','yes/no'],
                        ['B','conciseness'],
                        ['B','omit/delete'],
                        ['C','punctuation'],
                        ['D','adjectives/adverbs'],
                        ['D','punctuation'],
                        ['A','inference'],
                        ['B','passive voice'],
                        ['B','yes/no'],
                        ['D','conciseness'],
                        ['C','comparisons'],
                        ['A','punctuation'],
                        ['D','pronouns'],
                        ['C','yes/no']
                    ]
    },
    math: {
        scorescale: [
                        1, 4, 6, 8, 10, 11, 11, 12, 13, 13, 13, 14, 14, 15, 15, 15, 15,
                        16, 16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 20, 20, 21, 21,
                        22, 22, 23, 23, 23, 24, 24, 24, 25, 25, 26, 26, 26, 27, 27, 28,
                        28, 28, 29, 30, 30, 31, 32, 33, 34, 34, 35, 36
                    ],
        questions: [
                        ['D', '1-20'],
                        ['B', '1-20'],
                        ['C', '1-20'],
                        ['A', '1-20'],
                        ['A', '1-20'],
                        ['D', '1-20'],
                        ['C', '1-20'],
                        ['D', '1-20'],
                        ['B', '1-20'],
                        ['B', '1-20'],
                        ['B', '1-20'],
                        ['A', '1-20'],
                        ['D', '1-20'],
                        ['D', '1-20'],
                        ['D', '1-20'],
                        ['E', '1-20'],
                        ['B', '1-20'],
                        ['B', '1-20'],
                        ['C', '1-20'],
                        ['E', '1-20'],
                        ['E', '21-40'],
                        ['C', '21-40'],
                        ['B', '21-40'],
                        ['A', '21-40'],
                        ['C', '21-40'],
                        ['C', '21-40'],
                        ['B', '21-40'],
                        ['B', '21-40'],
                        ['E', '21-40'],
                        ['D', '21-40'],
                        ['C', '21-40'],
                        ['D', '21-40'],
                        ['E', '21-40'],
                        ['C', '21-40'],
                        ['C', '21-40'],
                        ['E', '21-40'],
                        ['B', '21-40'],
                        ['B', '21-40'],
                        ['E', '21-40'],
                        ['D', '21-40'],
                        ['E', '41-60'],
                        ['D', '41-60'],
                        ['A', '41-60'],
                        ['A', '41-60'],
                        ['E', '41-60'],
                        ['E', '41-60'],
                        ['D', '41-60'],
                        ['C', '41-60'],
                        ['E', '41-60'],
                        ['C', '41-60'],
                        ['B', '41-60'],
                        ['A', '41-60'],
                        ['D', '41-60'],
                        ['A', '41-60'],
                        ['D', '41-60'],
                        ['A', '41-60'],
                        ['A', '41-60'],
                        ['E', '41-60'],
                        ['C', '41-60'],
                        ['A', '41-60']
                    ]
    },
    reading: {
        scorescale: [
                        1, 2, 4, 5, 7, 8, 9, 10, 11, 11, 12, 13, 13, 14, 15, 15, 16, 16,
                        17, 18, 18, 19, 20, 20, 21, 22, 22, 23, 23, 24, 25, 26, 27, 28,
                        29, 30, 31, 32, 33, 34, 36
                    ],
        questions: [
                        ['B' , 'big picture'],
                        ['C' , 'detail'],
                        ['A' , 'detail'],
                        ['D' , 'inference'],
                        ['C' , 'purpose'],
                        ['D' , 'vocab in context'],
                        ['B' , 'detail'],
                        ['C' , 'detail'],
                        ['B' , 'inference'],
                        ['B' , 'detail'],
                        ['A' , 'big picture'],
                        ['D' , 'detail'],
                        ['C' , 'detail'],
                        ['D' , 'purpose'],
                        ['C' , 'purpose'],
                        ['C' , 'vocab in context'],
                        ['B' , 'detail'],
                        ['A' , 'inference'],
                        ['D' , 'detail'],
                        ['A' , 'inference'],
                        ['C' , 'big picture'],
                        ['A' , 'purpose'],
                        ['C' , 'inference'],
                        ['B' , 'detail'],
                        ['D' , 'detail'],
                        ['D' , 'vocab in context'],
                        ['B' , 'detail'],
                        ['A' , 'detail'],
                        ['C' , 'detail'],
                        ['A' , 'detail'],
                        ['B' , 'inference'],
                        ['D' , 'detail'],
                        ['D' , 'detail'],
                        ['D' , 'detail'],
                        ['B' , 'inference'],
                        ['D' , 'detail'],
                        ['A' , 'vocab in context'],
                        ['C' , 'detail'],
                        ['B' , 'detail'],
                        ['C' , 'detail']
                    ]
    },
    science: {
        scorescale: [
                        1, 3, 4, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 15, 16, 17, 17, 18,
                        19, 19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 25, 26, 27,  
                        27, 28, 30, 31, 32, 34, 36
                    ],
        questions: [
                        ['D' , 'detail'],
                        ['B' , 'trend'],
                        ['D' , 'outside information'],
                        ['C' , 'trend'],
                        ['B' , 'detail'],
                        ['D' , 'detail'],
                        ['C' , 'trend'],
                        ['B' , 'new information'],
                        ['A' , 'detail'],
                        ['C' , 'inference'],
                        ['A' , 'inference'],
                        ['A' , 'detail'],
                        ['C' , 'detail'],
                        ['A' , 'detail'],
                        ['A' , 'detail'],
                        ['D' , 'detail'],
                        ['B' , 'detail'],
                        ['D' , 'new information'],
                        ['C' , 'detail'],
                        ['C' , 'detail'],
                        ['A' , 'trend'],
                        ['D' , 'new information'],
                        ['B' , 'method'],
                        ['B' , 'new information'],
                        ['B' , 'detail'],
                        ['C' , 'detail'],
                        ['A' , 'new information'],
                        ['A' , 'new information'],
                        ['D' , 'trend'],
                        ['C' , 'detail'],
                        ['A' , 'detail'],
                        ['B' , 'new information'],
                        ['D' , 'trend'],
                        ['B' , 'method'],
                        ['D' , 'detail'],
                        ['C' , 'detail'],
                        ['B' , 'trend'],
                        ['D' , 'detail'],
                        ['C' , 'new information'],
                        ['D' , 'detail']
                    ]
    },
}

const a09 = {
    id: 'a09',
    english:{
        scorescale: [
                        1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 8, 9, 9, 10, 10, 10,
                        11, 11, 11, 12, 12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 15, 16,
                        16, 16, 17, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 22, 22, 22, 
                        23, 23, 23, 24, 24, 24, 25, 25, 25, 26, 27, 27, 28, 29, 30, 30, 
                        31, 33, 34, 35, 35, 35, 36, 36
                    ],
        questions: [
                        ['C' , 'punctuation'],
                        ['A' , 'punctuation'],
                        ['B' , 'yes/no'],
                        ['B' , 'possessives'],
                        ['B' , 'transitions'],
                        ['C' , 'punctuation'],
                        ['A' , 'vocab in context'],
                        ['D' , 'conciseness'],
                        ['A' , 'inference'],
                        ['C' , 'prepositions'],
                        ['D' , 'placement'],
                        ['C' , 'vocab in context'],
                        ['B' , 'inference'],
                        ['D' , 'punctuation'],
                        ['C' , 'prepositions'],
                        ['A' , 'punctuation'],
                        ['B' , 'inference'],
                        ['D' , 'verb tense'],
                        ['C' , 'parallelism'],
                        ['D' , 'omit/delete'],
                        ['B' , 'inference'],
                        ['D' , 'conciseness'],
                        ['A' , 'punctuation'],
                        ['B' , 'vocab in context'],
                        ['B' , 'vagueness'],
                        ['B' , 'conciseness'],
                        ['C' , 'inference'],
                        ['D' , 'placement'],
                        ['A' , 'inference'],
                        ['D' , 'verb tense'],
                        ['D' , 'inference'],
                        ['B' , 'punctuation'],
                        ['A' , 'punctuation'],
                        ['C' , 'vocab in context'],
                        ['C' , 'adjectives / adverbs'],
                        ['B' , 'conciseness'],
                        ['C' , 'vocab in context'],
                        ['A' , 'transitions'],
                        ['C' , 'inference'],
                        ['A' , 'conciseness'],
                        ['B' , 'omit/delete'],
                        ['D' , 'inference'],
                        ['D' , 'conciseness'],
                        ['A' , 'punctuation'],
                        ['C' , 'yes/no'],
                        ['B' , 'vocab in context'],
                        ['A' , 'comparisons'],
                        ['A' , 'prepositions'],
                        ['D' , 'conciseness'],
                        ['D' , 'conciseness'],
                        ['B' , 'parallelism'],
                        ['D' , 'omit/delete'],
                        ['C' , 'conciseness'],
                        ['A' , 'inference'],
                        ['B' , 'inference'],
                        ['A' , 'vagueness'],
                        ['C' , 'transitions'],
                        ['D' , 'possessives'],
                        ['C' , 'inference'],
                        ['C' , 'yes/no'],
                        ['B' , 'inference'],
                        ['C' , 'vocab in contex'],
                        ['C' , 'prepositions'],
                        ['D' , 'conciseness'],
                        ['D' , 'inference'],
                        ['C' , 'parallelism'],
                        ['A' , 'conciseness'],
                        ['D' , 'pronouns'],
                        ['C' , 'conciseness'],
                        ['A' , 'punctuation'],
                        ['A' , 'conciseness'],
                        ['D' , 'inference'],
                        ['A' , 'contractions'],
                        ['B' , 'punctuation'],
                        ['B' , 'yes/no'],
                    ]
    },
    math: {
        scorescale: [
                        1, 5, 7, 9, 11, 12, 12, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
                        17, 17, 17, 18, 18, 18, 19, 19, 20, 20, 21, 22, 22, 23, 23, 24, 24,
                        24, 25, 25, 25, 26, 26, 26, 27, 27, 27, 28, 28, 28, 29, 29, 30, 31, 
                        31, 32, 33, 33, 34, 35, 35, 36, 36
                    ],
        questions: [
                        ['A', '1-20'],
                        ['D', '1-20'],
                        ['C', '1-20'],
                        ['E', '1-20'],
                        ['C', '1-20'],
                        ['C', '1-20'],
                        ['A', '1-20'],
                        ['B', '1-20'],
                        ['E', '1-20'],
                        ['B', '1-20'],
                        ['D', '1-20'],
                        ['B', '1-20'],
                        ['B', '1-20'],
                        ['D', '1-20'],
                        ['E', '1-20'],
                        ['E', '1-20'],
                        ['E', '1-20'],
                        ['D', '1-20'],
                        ['A', '1-20'],
                        ['B', '1-20'],
                        ['A', '21-40'],  
                        ['D', '21-40'],   
                        ['A', '21-40'],
                        ['B', '21-40'],   
                        ['C', '21-40'],
                        ['C', '21-40'],  
                        ['C', '21-40'],   
                        ['C', '21-40'],
                        ['D', '21-40'],   
                        ['B', '21-40'],
                        ['D', '21-40'],  
                        ['C', '21-40'],   
                        ['A', '21-40'],
                        ['A', '21-40'],   
                        ['B', '21-40'],
                        ['B', '21-40'],  
                        ['E', '21-40'],   
                        ['D', '21-40'],
                        ['D', '21-40'],   
                        ['E', '21-40'],  
                        ['B', '41-60'],
                        ['A', '41-60'],
                        ['C', '41-60'],
                        ['A', '41-60'],
                        ['A', '41-60'],   
                        ['C', '41-60'],
                        ['B', '41-60'],
                        ['E', '41-60'],
                        ['E', '41-60'],
                        ['C', '41-60'],
                        ['D', '41-60'],
                        ['D', '41-60'],
                        ['B', '41-60'],
                        ['D', '41-60'],
                        ['D', '41-60'],
                        ['A', '41-60'],
                        ['A', '41-60'],
                        ['A', '41-60'],
                        ['E', '41-60'],
                        ['E', '41-60']   
                    ]
    },
    reading: {
        scorescale: [
                        1, 2, 4, 5, 6, 8, 9, 10, 10, 11, 12, 12, 13, 14, 14, 15, 16, 17, 17,
                        18, 19, 19, 20, 21, 22, 22, 23, 24, 24, 25, 26, 28, 29, 30, 31, 32,
                        33, 34, 35, 36, 36
                    ],
        questions: [
                        ['D' , 'detail'],
                        ['C' , 'purpose'],
                        ['B' , 'inference'],
                        ['C' , 'inference'],
                        ['A' , 'inference'],
                        ['D' , 'detail'],
                        ['B' , 'vocab in context'],
                        ['D' , 'detail'],
                        ['D' , 'purpose'],
                        ['C' , 'detail'],
                        ['C' , 'big picture'],
                        ['B' , 'purpose'],
                        ['C' , 'inference'],
                        ['D' , 'inference'],
                        ['B' , 'detail'],
                        ['A' , 'detail'],
                        ['C' , 'detail'],
                        ['B' , 'vocab in context'],
                        ['D' , 'inference'],
                        ['A' , 'detail'],
                        ['C' , 'purpose'],
                        ['C' , 'inference'],
                        ['D' , 'vocab in context'],
                        ['A' , 'inference'],
                        ['D' , 'inference'],
                        ['A' , 'inference'],
                        ['C' , 'vocab in context'],
                        ['B' , 'big picture'],
                        ['A' , 'big picture'],
                        ['B' , 'big picture'],
                        ['D' , 'big picture'],
                        ['A' , 'inference'],
                        ['B' , 'inference'],
                        ['B' , 'detail'],
                        ['C' , 'detail'],
                        ['D' , 'detail'],
                        ['A' , 'detail'],
                        ['C' , 'inference'],
                        ['C' , 'vocab in context'],
                        ['B' , 'inference']
                    ]
    },
    science: {
        scorescale: [
                        1, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 15, 16, 17, 17, 18, 18,
                        19, 20, 20, 21, 21, 22, 22, 23, 23, 24, 24, 25, 26, 27, 28, 29, 30, 31,
                        33, 34, 35, 36
                    ],
        questions: [
                        ['C' , 'new information'],
                        ['A' , 'inference'],
                        ['B' , 'inference'],
                        ['D' , 'inference'],
                        ['C' , 'new information'],
                        ['C' , 'inference'],
                        ['A' , 'inference'],
                        ['A' , 'detail'],
                        ['A' , 'detail'],
                        ['C' , 'detail'],
                        ['D' , 'new information'],
                        ['A' , 'new information'],
                        ['B' , 'inference'],
                        ['B' , 'detail'],
                        ['C' , 'new information'],
                        ['D' , 'inference'],
                        ['C' , 'new information'],
                        ['B' , 'inference'],
                        ['C' , 'detail'],
                        ['D' , 'new information'],
                        ['A' , 'detail'],
                        ['A' , 'detail'],
                        ['D' , 'detail'],
                        ['B' , 'new information'],
                        ['D' , 'new information'],
                        ['A' , 'new information'],
                        ['C' , 'new information'],
                        ['C' , 'inference'],
                        ['A' , 'inference'],
                        ['D' , 'inference'],
                        ['B' , 'inference'],
                        ['D' , 'inference'],
                        ['A' , 'inference'],
                        ['B' , 'detail'],
                        ['A' , 'detail'],
                        ['C' , 'inference'],
                        ['D' , 'detail'],
                        ['B' , 'detail'],
                        ['D' , 'detail'],
                        ['D' , 'detail']
                    ]
    },
}

const b05 = {
    id: 'b05',
    english:{
        scorescale: [
            1, 1, 2, 3, 4, 4, 5, 5, 6, 7, 7, 8, 8, 8, 9, 9, 10, 10, 10,
            11, 11, 11, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 15, 16, 16,
            17, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23,
            24, 24, 24, 25, 25, 26,26, 27, 28, 29, 30, 31, 32, 33, 34, 34, 35, 35, 35, 35,
            36, 36, 36
        ],
        questions: [
                    ['A','parallelism'],
                    ['B','inference'],
                    ['D','verb tense'],
                    ['C','punctuation'],
                    ['A','conciseness'],
                    ['C','modifying clauses'],
                    ['B','punctuation'],
                    ['B','ambiguity'],
                    ['A','conciseness'],
                    ['D','conciseness'],
                    ['C','conciseness'],
                    ['B','transitions'],
                    ['A','punctuation'],
                    ['B','inference'],
                    ['C','placement'],
                    ['B','subject/verb agreement'],
                    ['C','parallelism'],
                    ['B','pronouns'],
                    ['D','modifying clauses'],
                    ['C','possessives'],
                    ['D','conciseness'],
                    ['A','punctuation'],
                    ['D','conciseness'],
                    ['A','conciseness'],
                    ['D','omit/delete'],
                    ['A','inference'],
                    ['A','omit/delete'],
                    ['C','inference'],
                    ['D','conciseness'],
                    ['A','conciseness'],
                    ['A','punctuation'],
                    ['B','vocab in context'],
                    ['C','inference'],
                    ['A','conciseness'],
                    ['D','conciseness'],
                    ['A','punctuation'],
                    ['C','punctuation'],
                    ['D','subject/verb agreement'],
                    ['D','omit/delete'],
                    ['B','parallelism'],
                    ['A','conciseness'],
                    ['D','transitions'],
                    ['B','placement'],
                    ['C','inference'],
                    ['B','placement'],
                    ['D','conciseness'],
                    ['D','transitions'],
                    ['B','omit/delete'],
                    ['A','conciseness'],
                    ['B','inference'],
                    ['C','omit/delete'],
                    ['A','punctuation'],
                    ['D','yes/no'],
                    ['B','conciseness'],
                    ['A','possessives'],
                    ['D','transitions'],
                    ['C','conciseness'],
                    ['D','verb tense'],
                    ['D','placement'],
                    ['C','yes/no'],
                    ['D','modifying clauses'],
                    ['B','omit/delete'],
                    ['B','punctuation'],
                    ['D','conciseness'],
                    ['D','inference'],
                    ['B','pronouns'],
                    ['C','inference'],
                    ['C','punctuation'],
                    ['D','possessives'],
                    ['B','inference'],
                    ['A','transitions'],
                    ['C','placement'],
                    ['C','yes/no'],
                    ['B','punctuation'],
                    ['C','transitions']
                ]
    },
    math: {
        scorescale: [
                        1, 4, 6, 8, 9, 10, 11, 12, 12, 13, 13, 14, 14, 14, 14,
                        15, 15, 15, 16, 16, 16, 16, 17, 17, 18, 18, 18, 19, 20, 20,
                        21, 22, 22, 23, 24, 24, 25, 25, 26, 26, 26, 27, 27, 28, 28, 28,
                        29, 29, 30, 30, 31, 31, 32, 33, 33, 34, 35, 35, 35, 36, 36
                    ],
        questions: [
                    ['D', '1-20'],
                    ['B', '1-20'],
                    ['D', '1-20'],
                    ['A', '1-20'],
                    ['C', '1-20'],
                    ['B', '1-20'],
                    ['C', '1-20'],
                    ['A', '1-20'],
                    ['E', '1-20'],
                    ['B', '1-20'],
                    ['B', '1-20'],
                    ['D', '1-20'],
                    ['A', '1-20'],
                    ['D', '1-20'],
                    ['D', '1-20'],
                    ['E', '1-20'],
                    ['C', '1-20'],
                    ['E', '1-20'],
                    ['C', '1-20'],
                    ['C', '1-20'],
                    ['E', '21-40'],
                    ['C', '21-40'],
                    ['E', '21-40'],
                    ['D', '21-40'],
                    ['B', '21-40'],
                    ['C', '21-40'],
                    ['E', '21-40'],
                    ['A', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['B', '21-40'],
                    ['A', '21-40'],
                    ['B', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['C', '21-40'],
                    ['D', '21-40'],
                    ['B', '21-40'],
                    ['E', '21-40'],
                    ['E', '21-40'],
                    ['B', '41-60'],
                    ['B', '41-60'],
                    ['D', '41-60'],
                    ['A', '41-60'],
                    ['B', '41-60'],
                    ['A', '41-60'],
                    ['D', '41-60'],
                    ['B', '41-60'],
                    ['A', '41-60'],
                    ['D', '41-60'],
                    ['B', '41-60'],
                    ['B', '41-60'],
                    ['A', '41-60'],
                    ['D', '41-60'],
                    ['A', '41-60'],
                    ['D', '41-60'],
                    ['C', '41-60'],
                    ['E', '41-60'],
                    ['A', '41-60'],
                    ['A', '41-60'],
                ]
    },
    reading: {
        scorescale: [
                        1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 13, 14, 15, 15, 16, 17, 17,
                        18, 19, 19, 20, 21, 21, 22, 23, 24, 24, 25, 26, 27,28, 30, 31, 32, 33, 34, 35,
                        36
        ],
        questions: [
                    ['B', 'inference'],
                    ['C', 'vocab in context'],
                    ['C', 'purpose'],
                    ['B', 'detail'],
                    ['A', 'inference'],
                    ['B', 'purpose'],
                    ['D', 'vocab in context'],
                    ['A', 'detail'],
                    ['A', 'detail'],
                    ['C', 'detail'],
                    ['B', 'inference'],
                    ['D', 'big picture'],
                    ['D', 'purpose'],
                    ['C', 'purpose'],
                    ['A', 'purpose'],
                    ['C', 'detail'],
                    ['B', 'vocab in context'],
                    ['D', 'detail'],
                    ['B', 'vocab in context'],
                    ['A', 'detail'],
                    ['B', 'vocab in context'],
                    ['D', 'inference'],
                    ['C', 'detail'],
                    ['B', 'purpose'],
                    ['C', 'big picture'],
                    ['A', 'detail'],
                    ['B', 'detail'],
                    ['C', 'big picture'],
                    ['D', 'inference'],
                    ['D', 'detail'],
                    ['C', 'big picture'],
                    ['A', 'purpose'],
                    ['B', 'detail'],
                    ['D', 'inference'],
                    ['C', 'inference'],
                    ['C', 'detail'],
                    ['A', 'inference'],
                    ['D', 'inference'],
                    ['C', 'detail'],
                    ['D', 'detail']
        ]
    },
    science: {
        scorescale: [
                        1, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 17, 18, 18,
                        19 ,19, 20, 21, 21, 22, 23, 23, 24, 24, 25, 25, 26, 27, 28, 29, 30,
                        31, 33, 34, 35, 36, 36 
        ],
        questions: [
                    ['B', 'detail'],
                    ['C', 'new information'],
                    ['C', 'new information'],
                    ['C', 'trend'],
                    ['D', 'outside information'],
                    ['A', 'new information'],
                    ['A', 'trend'],
                    ['B', 'new information'],
                    ['C', 'method'],
                    ['C', 'detail'],
                    ['B', 'detail'],
                    ['D', 'trend'],
                    ['D', 'trend'],
                    ['B', 'new information'],
                    ['C', 'method'],
                    ['A', 'new information'],
                    ['B', 'new information'],
                    ['A', 'trend'],
                    ['A', 'method'],
                    ['D', 'detail'],
                    ['A', 'detail'],
                    ['D', 'detail'],
                    ['C', 'detail'],
                    ['A', 'detail'],
                    ['D', 'detail'],
                    ['A', 'trend'],
                    ['B', 'trend'],
                    ['B', 'trend'],
                    ['D', 'detail'],
                    ['C', 'new information'],
                    ['A', 'detail'],
                    ['A', 'new information'],
                    ['C', 'detail'],
                    ['A', 'new information'],
                    ['A', 'detail'],
                    ['A', 'detail'],
                    ['C', 'detail'],
                    ['A', 'new information'],
                    ['D', 'outside information'],
                    ['D', 'trend']
        ]
    },
}

const z15 = {
    id: 'z15',
    english:{
        scorescale: [1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 10, 11, 11, 11, 12, 12, 13, 13, 14, 14, 
                    15, 15, 15, 15, 16, 16, 17, 17, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 22,
                    23, 23, 23, 24, 24, 24, 25, 25, 26, 26, 27, 27, 28, 29, 29, 30, 31, 32, 33, 33, 34, 35, 35, 35, 36, 36],
        questions: [
                        ['D','modifying clauses'],
                        ['B','inference'],
                        ['A','punctuation'],
                        ['B','punctuation'],
                        ['D','conciseness'],
                        ['D','conciseness'],
                        ['B','comparisons'],
                        ['B','vocab in context'],
                        ['C','inference'],
                        ['C','prepositions'],
                        ['C','pronouns'],
                        ['B','inference'],
                        ['D','conciseness'],
                        ['A','yes/no'],
                        ['C','punctuation'],
                        ['B','conciseness'],
                        ['A','comparisons'],
                        ['A','yes/no'],
                        ['D','conciseness'],
                        ['C','inference'],
                        ['B','parallelism'],
                        ['C','placement'],
                        ['D','conciseness'],
                        ['A','punctuation'],
                        ['B','punctuation'],
                        ['D','subject/verb agreement'],
                        ['A','vocab in context'],
                        ['C','punctuation'],
                        ['A','vocab in context'],
                        ['C','yes/no'],
                        ['B','punctuation'],
                        ['C','inference'],
                        ['B','punctuation'],
                        ['D','parallelism'],
                        ['D','prepositions'],
                        ['D','conciseness'],
                        ['A','conciseness'],
                        ['D','placement'],
                        ['C','omit/delete'],
                        ['C','inference'],
                        ['D','inference'],
                        ['B','inference'],
                        ['A','subject/verb agreement'],
                        ['D','omit/delete'],
                        ['C','placement'],
                        ['B','punctuation'],
                        ['C','pronouns'],
                        ['A','punctuation'],
                        ['D','punctuation'],
                        ['A','possessives'],
                        ['A','inference'],
                        ['C','punctuation'],
                        ['A','conciseness'],
                        ['D','conciseness'],
                        ['D','conciseness'],
                        ['B','transitions'],
                        ['A','punctuation'],
                        ['B','inference'],
                        ['D','verb tense'],
                        ['C','yes/no'],
                        ['D','parallelism'],
                        ['D','punctuation'],
                        ['D','transitions'],
                        ['C','pronouns'],
                        ['A','inference'],
                        ['B','punctuation'],
                        ['A','inference'],
                        ['C','inference'],
                        ['B','vocab in context'],
                        ['B','inference'],
                        ['C','placement'],
                        ['A','inference'],
                        ['C','prepositions'],
                        ['D','transitions'],
                        ['A','omit/delete'],
                ]
    },
    math: {
        scorescale: [
                        1, 4, 7, 8, 10, 11, 12, 12, 13, 13, 14, 14, 15, 15, 15, 15,
                        16, 16 ,16 ,16, 17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 
                        21, 21, 22, 22, 23, 23, 24, 24, 24, 25, 25, 26, 26, 26, 
                        27, 27, 27, 28, 28, 28, 29, 29, 30, 31, 32, 33, 34, 35,
                        35, 36, 36
        ],
        questions: [
                    ['A', '1-20'],
                    ['D', '1-20'],
                    ['B', '1-20'],
                    ['C', '1-20'],
                    ['C', '1-20'],
                    ['B', '1-20'],
                    ['A', '1-20'],
                    ['B', '1-20'],
                    ['A', '1-20'],
                    ['A', '1-20'],
                    ['B', '1-20'],
                    ['A', '1-20'],
                    ['A', '1-20'],
                    ['C', '1-20'],
                    ['A', '1-20'],
                    ['D', '1-20'],
                    ['E', '1-20'],
                    ['A', '1-20'],
                    ['E', '1-20'],
                    ['C', '1-20'],
                    ['E', '21-40'],
                    ['E', '21-40'],
                    ['D', '21-40'],
                    ['E', '21-40'],
                    ['C', '21-40'],
                    ['A', '21-40'],
                    ['B', '21-40'],
                    ['C', '21-40'],
                    ['D', '21-40'],
                    ['D', '21-40'],
                    ['E', '21-40'],
                    ['C', '21-40'],
                    ['E', '21-40'],
                    ['B', '21-40'],
                    ['C', '21-40'],
                    ['A', '21-40'],
                    ['D', '21-40'],
                    ['B', '21-40'],
                    ['E', '21-40'],
                    ['D', '21-40'],
                    ['E', '41-60'],
                    ['B', '41-60'],
                    ['C', '41-60'],
                    ['A', '41-60'],
                    ['A', '41-60'],
                    ['E', '41-60'],
                    ['D', '41-60'],
                    ['D', '41-60'],
                    ['D', '41-60'],
                    ['B', '41-60'],
                    ['B', '41-60'],
                    ['C', '41-60'],
                    ['C', '41-60'],
                    ['E', '41-60'],
                    ['A', '41-60'],
                    ['E', '41-60'],
                    ['D', '41-60'],
                    ['B', '41-60'],
                    ['C', '41-60'],
                    ['B', '41-60']
                ]
    },
    reading: {
        scorescale: [
            1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 12, 13, 14, 15, 15, 16, 17, 17, 18, 19, 20, 20,
            21, 22, 22, 23, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36
        ],
        questions: [
                    ['C','big picture'],
                    ['C','inference'],
                    ['D','detail'],
                    ['A','inference'],
                    ['C','inference'],
                    ['D','detail'],
                    ['D','inference'],
                    ['B','detail'],
                    ['C','inference'],
                    ['D','inference'],
                    ['A','big picture'],
                    ['B','inference'],
                    ['D','inference'],
                    ['C','purpose'],
                    ['B','detail'],
                    ['A','inference'],
                    ['B','detail'],
                    ['A','detail'],
                    ['B','inference'],
                    ['C','detail'],
                    ['B','purpose'],
                    ['B','detail'],
                    ['C','vocab in context'],
                    ['C','inference'],
                    ['C','inference'],
                    ['B','detail'],
                    ['B','vocab in context'],
                    ['A','big picture'],
                    ['D','big picture'],
                    ['A','inference'],
                    ['B','big picture'],
                    ['B','purpose'],
                    ['D','detail'],
                    ['D','purpose'],
                    ['C','detail'],
                    ['A','detail'],
                    ['B','detail'],
                    ['C','detail'],
                    ['A','inference'],
                    ['A','inference']
        ]
    },
    science: {
        scorescale: [
            1, 3, 5, 6, 8, 9, 10, 11, 12, 13, 13, 14, 15, 16, 16, 17, 18, 18, 19, 20,
            20, 21, 21, 22, 22, 23, 24, 24, 25, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 36
        ],
        questions: [
                    ['D', 'detail'],
                    ['C', 'trend'],
                    ['A', 'method'],
                    ['B', 'detail'],
                    ['A', 'inference'],
                    ['C', 'new information'],
                    ['B', 'trend'],
                    ['B', 'new information'],
                    ['D', 'inference'],
                    ['D', 'detail'],
                    ['A', 'outside information'],
                    ['C', 'inference'],
                    ['A', 'outside information'],
                    ['B', 'method'],
                    ['C', 'new information'],
                    ['A', 'new information'],
                    ['D', 'detail'],
                    ['C', 'new information'],
                    ['B', 'detail'],
                    ['D', 'new information'],
                    ['A', 'trend'],
                    ['C', 'detail'],
                    ['D', 'new information'],
                    ['D', 'detail'],
                    ['D', 'new information'],
                    ['C', 'new information'],
                    ['A', 'new information'],
                    ['D', 'trend'],
                    ['B', 'new information'],
                    ['C', 'detail'],
                    ['C', 'trend'],
                    ['D', 'detail'],
                    ['A', 'new information'],
                    ['A', 'method'],
                    ['B', 'detail'],
                    ['A', 'detail'],
                    ['C', 'outside information'],
                    ['A', 'detail'],
                    ['D', 'detail'],
                    ['B', 'detail'],
        ]
    },
}

const c61 = {
    id: '61c',
    english:{
        scorescale: [
            1,  1,  2,  2,  3,  3,  4,  4,
            5,  5,  6,  6,  6,  7,  7,  8,
            8,  8,  9,  9, 10, 10, 11, 11,
            12, 12, 13, 13, 14, 14, 15, 15,
            15, 15, 16, 16, 16, 17, 17, 18,
            18, 18, 19, 19, 20, 20, 20, 21,
            21, 21, 22, 22, 22, 23, 23, 24,
            24, 25, 25, 25, 26, 26, 27, 27,
            28, 29, 29, 30, 31, 32, 33, 34,
            34, 35, 35, 36
        ],
        questions: [
            ['D', 'conciseness' ], 
            ['A', 'conciseness' ], 
            ['B', 'punctuation' ], 
            ['D', 'conciseness' ],
            ['A', 'punctuation' ], 
            ['B', 'modifying clauses' ], 
            ['A', 'punctuation' ], 
            ['B', 'verb tense' ],
            ['A', 'pronouns' ], 
            ['D', 'yes/no' ], 
            ['C', 'inference' ], 
            ['D', 'verb tense' ],
            ['A', 'inference' ], 
            ['B', 'punctuation' ], 
            ['C', 'placement' ], 
            ['D', 'vocab in context' ],
            ['B', 'punctuation' ], 
            ['D', 'omit/delete' ], 
            ['A', 'vocab in context' ], 
            ['A', 'inference' ],
            ['C', 'transitions' ], 
            ['A', 'omit/delete' ], 
            ['A', 'punctuation' ], 
            ['D', 'pronouns' ],
            ['B', 'transitions' ], 
            ['A', 'inference' ], 
            ['A', 'pronouns' ], 
            ['C', 'inference' ],
            ['D', 'conciseness' ], 
            ['B', 'transitions' ], 
            ['C', 'inference' ], 
            ['D', 'vocab in context' ],
            ['A', 'inference' ], 
            ['C', 'punctuation' ], 
            ['C', 'prepositions' ], 
            ['B', 'punctuation' ],
            ['D', 'conciseness' ], 
            ['C', 'pronouns' ], 
            ['A', 'pronouns' ], 
            ['D', 'transitions' ],
            ['C', 'verb tense' ], 
            ['A', 'inference' ], 
            ['C', 'punctuation' ], 
            ['A', 'prepositions' ],
            ['D', 'yes/no' ], 
            ['B', 'transitions' ], 
            ['A', 'inference' ], 
            ['B', 'punctuation' ],
            ['D', 'conciseness' ], 
            ['B', 'pronouns' ], 
            ['C', 'conciseness' ], 
            ['C', 'punctuation' ],
            ['B', 'omit/delete' ], 
            ['D', 'punctuation' ], 
            ['D', 'conciseness' ], 
            ['D', 'inference' ],
            ['C', 'pronouns' ], 
            ['C', 'inference' ], 
            ['B', 'inference' ], 
            ['D', 'inference' ],
            ['C', 'ambiguity/vagueness' ], 
            ['A', 'punctuation' ], 
            ['B', 'inference' ], 
            ['A', 'prepositions' ],
            ['D', 'inference' ], 
            ['C', 'modifying clauses' ], 
            ['B', 'pronouns' ], 
            ['B', 'punctuation' ],
            ['C', 'ambiguity/vagueness' ], 
            ['D', 'conciseness' ], 
            ['D', 'inference' ], 
            ['A', 'conciseness' ],
            ['B', 'conciseness' ], 
            ['C', 'pronouns' ], 
            ['D', 'punctuation' ]
          ]
    },
    math: {
        scorescale: [
            1,  3,  6,  7,  9, 10, 11,
           11, 12, 13, 13, 13, 14, 14,
           14, 15, 15, 15, 16, 16, 16,
           16, 17, 17, 17, 18, 18, 19,
           19, 19, 20, 21, 21, 22, 22,
           23, 23, 24, 24, 25, 25, 26,
           26, 27, 27, 27, 28, 28, 29,
           29, 30, 30, 31, 31, 32, 33,
           34, 34, 35, 35, 36
        ],
        questions: [
                    [ 'A', '1-20' ],  [ 'E', '1-20' ],  [ 'B', '1-20' ],
                    [ 'B', '1-20' ],  [ 'E', '1-20' ],  [ 'C', '1-20' ],
                    [ 'E', '1-20' ],  [ 'B', '1-20' ],  [ 'B', '1-20' ],
                    [ 'D', '1-20' ],  [ 'E', '1-20' ],  [ 'D', '1-20' ],
                    [ 'B', '1-20' ],  [ 'B', '1-20' ],  [ 'C', '1-20' ],
                    [ 'B', '1-20' ],  [ 'A', '1-20' ],  [ 'C', '1-20' ],
                    [ 'C', '1-20' ],  [ 'E', '1-20' ], [ 'B', '21-40' ],
                    [ 'E', '21-40' ], [ 'A', '21-40' ], [ 'A', '21-40' ],
                    [ 'D', '21-40' ], [ 'D', '21-40' ], [ 'A', '21-40' ],
                    [ 'C', '21-40' ], [ 'C', '21-40' ], [ 'B', '21-40' ],
                    [ 'E', '21-40' ], [ 'A', '21-40' ], [ 'C', '21-40' ],
                    [ 'D', '21-40' ], [ 'B', '21-40' ], [ 'E', '21-40' ],
                    [ 'C', '21-40' ], [ 'D', '21-40' ], [ 'C', '21-40' ],
                    [ 'C', '21-40' ], [ 'A', '21-40' ], [ 'A', '41-60' ],
                    [ 'D', '41-60' ], [ 'A', '41-60' ], [ 'C', '41-60' ],
                    [ 'E', '41-60' ], [ 'C', '41-60' ], [ 'D', '41-60' ],
                    [ 'D', '41-60' ], [ 'D', '41-60' ], [ 'E', '41-60' ],
                    [ 'D', '41-60' ], [ 'A', '41-60' ], [ 'E', '41-60' ],
                    [ 'B', '41-60' ], [ 'C', '41-60' ], [ 'A', '41-60' ],
                    [ 'E', '41-60' ], [ 'E', '41-60' ], [ 'D', '41-60' ]
         ]
    },
    reading: {
        scorescale: [
            1,  2,  4,  5,  6,  8,
            9, 10, 11, 11, 12, 12,
           13, 13, 14, 14, 15, 16,
           16, 17, 18, 19, 20, 21,
           22, 23, 24, 25, 26, 27,
           28, 28, 29, 30, 32, 33,
           34, 35, 36, 36, 36
        ],
        questions: [
            [ 'B', 'big picture' ],
            [ 'D', 'inference' ],
            [ 'C', 'purpose' ],
            [ 'A', 'purpose' ],
            [ 'C', 'inference' ],
            [ 'D', 'detail' ],
            [ 'A', 'purpose' ],
            [ 'C', 'inference' ],
            [ 'D', 'detail' ],
            [ 'B', 'inference' ],
            [ 'B', 'big picture' ],
            [ 'A', 'detail' ],
            [ 'D', 'detail' ],
            [ 'D', 'inference' ],
            [ 'D', 'inference' ],
            [ 'B', 'purpose' ],
            [ 'A', 'purpose' ],
            [ 'A', 'detail' ],
            [ 'C', 'detail' ],
            [ 'C', 'inference' ],
            [ 'A', 'big picture' ],
            [ 'C', 'inference' ],
            [ 'C', 'purpose' ],
            [ 'D', 'detail' ],
            [ 'D', 'inference' ],
            [ 'B', 'inference' ],
            [ 'D', 'vocab in context' ],
            [ 'A', 'purpose' ],
            [ 'C', 'inference' ],
            [ 'B', 'inference' ],
            [ 'B', 'big picture' ],
            [ 'D', 'inference' ],
            [ 'B', 'inference' ],
            [ 'C', 'purpose' ],
            [ 'A', 'detail' ],
            [ 'A', 'purpose' ],
            [ 'C', 'inference' ],
            [ 'B', 'vocab in context' ],
            [ 'D', 'inference' ],
            [ 'C', 'inference' ]
        ]
    },
    science: {
        scorescale: [
            1,  3,  5,  7,  8,  9,
           10, 11, 12, 13, 14, 14,
           15, 16, 17, 17, 18, 18,
           19, 19, 19, 20, 20, 21,
           21, 22, 22, 23, 23, 24,
           25, 25, 26, 26, 27, 28,
           29, 30, 32, 34, 36
        ],
        questions: [
                    ['B', 'detail' ],
                    ['D', 'detail' ],
                    ['C', 'detail' ],
                    ['A', 'new information' ],
                    ['A', 'new information' ],
                    ['D', 'new information' ],
                    ['D', 'new information' ],
                    ['B', 'trend' ],
                    ['C', 'detail' ],
                    ['C', 'detail' ],
                    ['D', 'detail' ],
                    ['C', 'detail' ],
                    ['B', 'trend' ],
                    ['A', 'trend' ],
                    ['C', 'detail' ],
                    ['D', 'method' ],
                    ['A', 'method' ],
                    ['A', 'new information' ],
                    ['B', 'new information' ],
                    ['A', 'detail' ],
                    ['B', 'trend' ],
                    ['B', 'trend' ],
                    ['A', 'detail' ],
                    ['C', 'detail' ],
                    ['D', 'trend' ],
                    ['B', 'new information' ],
                    ['B', 'trend' ],
                    ['A', 'trend' ],
                    ['C', 'detail' ],
                    ['A', 'trend' ],
                    ['D', 'trend' ],
                    ['B', 'detail' ],
                    ['C', 'method' ],
                    ['D', 'method' ],
                    ['C', 'trend' ],
                    ['C', 'new information' ],
                    ['D', 'detail' ],
                    ['B', 'trend' ],
                    ['C', 'detail' ],
                    ['D', 'new information' ]
                ]
    },
}

const f72 = {
    id: '72F',
    english:{
        scorescale: [
            1,  1,  2,  2,  3,  3,  4,  5,
            5,  5,  6,  6,  7,  7,  7,  8,
            8,  9,  9,  9, 11, 11, 11, 12,
           12, 13, 13, 14, 14, 14, 14, 14,
           14, 14, 14, 14, 14, 14, 15, 15,
           15, 15, 16, 16, 17, 17, 18, 18,
           19, 19, 20, 20, 20, 21, 21, 21,
           22, 22, 23, 23, 23, 24, 24, 25,
           25, 26, 26, 27, 28, 28, 29, 30,
           30, 31, 32, 33, 33, 34, 35, 35,
           35, 36, 36
         ],
        questions: [
            [ 'B', 'inference' ],
            [ 'C', 'prepositions' ],
            [ 'B', 'inference' ],
            [ 'D', 'conciseness' ],
            [ 'A', 'conciseness' ],
            [ 'A', 'inference' ],
            [ 'A', 'conciseness' ],
            [ 'B', 'verb tense' ],
            [ 'A', 'punctuation' ],
            [ 'B', 'punctuation' ],
            [ 'B', 'inference' ],
            [ 'C', 'pronouns' ],
            [ 'C', 'inference' ],
            [ 'A', 'placement' ],
            [ 'D', 'yes/no' ],
            [ 'D', 'vocab' ],
            [ 'A', 'inference' ],
            [ 'B', 'verb tense' ],
            [ 'A', 'verb tense' ],
            [ 'A', 'punctuation' ],
            [ 'B', 'fixed expressions' ],
            [ 'B', 'parallelism' ],
            [ 'A', 'conciseness' ],
            [ 'C', 'inference' ],
            [ 'D', 'vocab in context' ],
            [ 'C', 'placement' ],
            [ 'B', 'punctuation' ],
            [ 'C', 'punctuation' ],
            [ 'B', 'modifying clauses' ],
            [ 'A', 'omit/delete' ],
            [ 'D', 'conciseness' ],
            [ 'C', 'inference' ],
            [ 'B', 'punctuation' ],
            [ 'A', 'transitions' ],
            [ 'B', 'conciseness' ],
            [ 'C', 'modifying' ],
            [ 'C', 'vagueness / ambiguity' ],
            [ 'C', 'yes/no' ],
            [ 'A', 'subject' ],
            [ 'A', 'omit/delete' ],
            [ 'B', 'inference' ],
            [ 'C', 'punctuation' ],
            [ 'B', 'inference' ],
            [ 'A', 'conciseness' ],
            [ 'D', 'conciseness' ],
            [ 'D', 'punctuation' ],
            [ 'C', 'punctuation' ],
            [ 'A', 'verb tense' ],
            [ 'B', 'yes/no' ],
            [ 'D', 'transitions' ],
            [ 'D', 'omit/delete' ],
            [ 'B', 'punctuation' ],
            [ 'D', 'modifying' ],
            [ 'A', 'verb tense' ],
            [ 'D', 'inference' ],
            [ 'B', 'punctuation' ],
            [ 'C', 'punctuation' ],
            [ 'C', 'transitions' ],
            [ 'D', 'verb tense' ],
            [ 'C', 'yes/no' ],
            [ 'D', 'conciseness' ],
            [ 'A', 'inference' ],
            [ 'A', 'subject/verb agreement' ],
            [ 'C', 'inference' ],
            [ 'A', 'conciseness/comparisons' ],
            [ 'D', 'conciseness/verb' ],
            [ 'D', 'verb tense' ],
            [ 'B', 'inference' ],
            [ 'D', 'punctuation/conciseness' ],
            [ 'C', 'placement' ],
            [ 'D', 'conciseness' ],
            [ 'D', 'inference' ],
            [ 'A', 'comparisons/verb' ],
            [ 'B', 'inference' ],
            [ 'C', 'placement' ]
          ]
    },
    math: {
        scorescale: [
            1,  4,  6,  8, 10, 11, 11,
           12, 13, 13, 14, 14, 14, 15,
           15, 15, 16, 16, 16, 16, 16,
           17, 17, 17, 18, 18, 18, 19,
           19, 20, 20, 21, 22, 22, 23,
           23, 24, 24, 24, 25, 25, 26,
           26, 26, 27, 27, 27, 28, 28,
           28, 29, 30, 30, 31, 32, 32,
           33, 34, 35, 35, 36
        ],
        questions: [
            [ 'E', 'simplify/backsolve' ],
            [ 'D', 'simplify/use' ],
            [ 'C', 'simplify' ],
            [ 'D', 'simplify' ],
            [ 'B', 'simplify' ],
            [ 'E', 'backsolve' ],
            [ 'B', 'simplify' ],
            [ 'A', 'backsolve' ],
            [ 'E', 'elimination/backsolve' ],
            [ 'A', 'pick' ],
            [ 'C', 'simplify' ],
            [ 'A', 'simplify' ],
            [ 'C', 'simplify' ],
            [ 'C', 'elimination' ],
            [ 'C', 'simplify' ],
            [ 'B', 'simplify' ],
            [ 'A', 'simplify' ],
            [ 'C', 'use' ],
            [ 'A', 'simplify' ],
            [ 'C', 'simplify' ],
            [ 'E', 'elimination' ],
            [ 'D', 'backsolve' ],
            [ 'D', 'simplify' ],
            [ 'B', 'simplify→' ],
            [ 'B', 'simplify' ],
            [ 'A', 'elimination' ],
            [ 'C', 'simplify' ],
            [ 'A', 'simplify' ],
            [ 'E', 'pick' ],
            [ 'D', 'simplify' ],
            [ 'C', 'simplify' ],
            [ 'E', 'elimination' ],
            [ 'B', 'simplify' ],
            [ 'E', 'simplify' ],
            [ 'C', 'simplify' ],
            [ 'B', 'simplify' ],
            [ 'D', 'simplify' ],
            [ 'D', 'elimination' ],
            [ 'C', 'backsolve' ],
            [ 'D', 'elimination' ],
            [ 'A', 'elimination' ],
            [ 'E', 'elimination' ],
            [ 'B', 'simplify' ],
            [ 'E', 'backsolve' ],
            [ 'A', 'simplify' ],
            [ 'A', 'simplify' ],
            [ 'E', 'pick' ],
            [ 'A', 'elimination/simplify' ],
            [ 'A', 'simplify' ],
            [ 'B', 'simplify' ],
            [ 'D', 'simplify/backsolve' ],
            [ 'D', 'simplify/pick' ],
            [ 'D', 'elimination' ],
            [ 'B', 'elimination' ],
            [ 'D', 'pick' ],
            [ 'A', 'elimination' ],
            [ 'E', 'simplify' ],
            [ 'B', 'simplify' ],
            [ 'D', 'simplify' ],
            [ 'B', 'simplify' ]
          ]
    },
    reading: {
        scorescale: [
            1,  3,  5,  6,  8,  9,
           10, 11, 12, 12, 13, 13,
           14, 14, 15, 16, 16, 17,
           18, 18, 19, 20, 20, 21,
           22, 22, 23, 23, 24, 25,
           26, 27, 28, 29, 30, 30,
           31, 32, 33, 34, 36
         ],
        questions: [
            [ 'C', 'purpose' ],     [ 'D', 'inference' ],
            [ 'D', 'purpose' ],     [ 'A', 'inference' ],
          [ 'D', 'inference' ],        [ 'C', 'detail' ],
              [ 'B', 'vocab' ],        [ 'D', 'detail' ],
          [ 'D', 'inference' ],        [ 'A', 'detail' ],
            [ 'A', 'purpose' ],        [ 'A', 'detail' ],
            [ 'D', 'purpose' ],       [ 'A', 'purpose' ],
              [ 'C', 'vocab' ],        [ 'C', 'detail' ],
          [ 'B', 'inference' ],        [ 'B', 'detail' ],
      [ 'C', 'inference/big' ],     [ 'B', 'inference' ],
          [ 'C', 'inference' ],     [ 'C', 'inference' ],
             [ 'D', 'detail' ],        [ 'A', 'detail' ],
          [ 'B', 'inference' ],     [ 'C', 'inference' ],
          [ 'C', 'inference' ],     [ 'D', 'inference' ],
          [ 'A', 'inference' ],     [ 'A', 'inference' ],
                [ 'D', 'big' ],     [ 'D', 'inference' ],
          [ 'C', 'inference' ],        [ 'C', 'detail' ],
             [ 'A', 'detail' ],     [ 'B', 'inference' ],
             [ 'A', 'detail' ],        [ 'B', 'detail' ],
             [ 'B', 'detail' ],        [ 'C', 'detail' ]
    ]
    },
    science: {
        scorescale: [
            1,  3,  5,  7,  8,  9,
           10, 11, 12, 13, 13, 14,
           15, 16, 16, 17, 18, 18,
           19, 19, 20, 20, 21, 21,
           22, 22, 23, 23, 24, 24,
           25, 26, 26, 27, 28, 29,
           30, 31, 33, 34, 36
         ],
        questions: [
            [ 'C', 'detail' ],
            [ 'C', 'detail' ],
            [ 'A', 'detail' ],
            [ 'A', 'detail' ],
            [ 'D', 'detail'],
            [ 'B', 'trend' ],
            [ 'D', 'detail' ],
            [ 'D', 'detail' ],
            [ 'C', 'inference' ],
            [ 'A', 'detail' ],
            [ 'C', 'detail' ],
            [ 'A', 'detail' ],
            [ 'A', 'detail' ],
            [ 'C', 'method' ],
            [ 'D', 'detail' ],
            [ 'B', 'detail' ],
            [ 'C', 'detail' ],
            [ 'D', 'trend' ],
            [ 'A', 'method' ],
            [ 'C', 'inference' ],
            [ 'A', 'inference' ],
            [ 'B', 'new information' ],
            [ 'B', 'new information' ],
            [ 'A', 'detail' ],
            [ 'D', 'detail' ],
            [ 'A', 'detail' ],
            [ 'D', 'detail' ],
            [ 'B', 'detail' ],
            [ 'B', 'trend' ],
            [ 'C', 'new information' ],
            [ 'B', 'new information' ],
            [ 'D', 'new information' ],
            [ 'C', 'new information' ],
            [ 'C', 'detail' ],
            [ 'B', 'method' ],
            [ 'D', 'trend' ],
            [ 'D', 'outside information' ],
            [ 'D', 'method' ],
            [ 'C', 'new information' ],
            [ 'A', 'new information' ]
          ]
    },
}

export default {
    a11,
    e73,
    a09,
    f67,
    z15,
    b05,
    c61
}
